### ISSUE TITLE
[BUG] VLC config not found when installed via Snap

### ISSUE THREAD

**Issue by obroomhall** [iamkroot/trakt-scrobbler#105]
A VLC installation via Snap causes configuration to be stored at ~/snap/vlc/common rather than the assumed ~/.config/vlc.

**Desktop:**
 - OS and Version: Ubuntu 20.04.2 LTS
 - Python Version: 3.8.5
 - Player and Version: VLC 3.0.12.1

**To Reproduce**:
1. Install vlc via snap
2. Configure and run trakts
4. See error in log file

**Temporary fix**:
1. Create a soft link to the snap config directory:
`mkdir ~/.config/vlc && ln ~/snap/vlc/common/vlcrc ~/.config/vlc`

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
2021-01-30 10:36:57,201 - INFO - MainThread - scrobbler - Started scrobbler thread.
2021-01-30 10:36:57,204 - ERROR - MainThread - monitor - Config value autoload failed for vlc.
Traceback (most recent call last):
  File "/home/oliver/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/player_monitors/monitor.py", line 64, in __new__
    cls.config = cls.autoload_cfg()
  File "/home/oliver/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/player_monitors/monitor.py", line 90, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "/home/oliver/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/player_monitors/vlc.py", line 59, in read_player_cfg
    raise FileNotFoundError(vlcrc_path)
FileNotFoundError: /home/oliver/.config/vlc/vlcrc
2021-01-30 10:36:57,205 - WARNING - MainThread - main - Could not start monitor for vlc
```
</p>
</details>

**Comment by iamkroot** [comment]
Ah that's tricky indeed. The scrobbler only looks inside `~/.config/vlc` for the config file. I can add other paths too, I guess.
But the simpler solution would be to just override the `trakts config set players.vlc` parameters which are set to `auto-detect` by default.

**Comment by obroomhall** [comment]
That solution is good enough for me, happy to close
