### ISSUE TITLE
[BUG] MPC-HC unhandled exception

### ISSUE THREAD

**Issue by Slikkster** [iamkroot/trakt-scrobbler#126]
I got this error last night when I was watching a show. Trakt only showed the episode as 44% watched even though I watched the whole thing, which is why I checked the log.

```
2021-06-25 22:45:55,820 - ERROR - mpc-hc - __init__ - Unhandled exception
Traceback (most recent call last):
  File "c:\users\slikk\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\__init__.py", line 32, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "c:\users\slikk\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 328, in run
    self.update_status()
  File "c:\users\slikk\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\mpc.py", line 42, in update_status
    if variables['duration'] == '0':
KeyError: 'duration'
```

**Comment by iamkroot** [comment]
Fixed in the latest beta.
