### ISSUE TITLE
[BUG] Error on installing latest beta

### ISSUE THREAD

**Issue by Hillgrove** [iamkroot/trakt-scrobbler#128]
**Describe the bug**

Running this command in CLI:
`pipx install --force --pip-args='--force-reinstall' git+https://github.com/iamkroot/trakt-scrobbler.git@v1.3.0-beta.1`

Returns this error:
 
```
ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/iamkroot/trakt-scrobbler.git 'C:\Users\Hillgrove\AppData\Local\Temp\pip-req-build-raj2265z'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Cannot determine package name from spec 'git+https://github.com/iamkroot/trakt-scrobbler.git@v1.3.0-beta.1'. Check package spec for errors.
```

A clear and concise description of what the bug/error is.

**Desktop (please complete the following information):**
 - OS and Version: Win 10 Pro
 - Python Version: 3.9.0
 - Player and Version: VLC 3.0.14

**To Reproduce**

See description

**Comment by iamkroot** [comment]
Yeah, when trying to install directly from the github url, you'll need to have [git](https://git-scm.com/) installed. 
But since this is a beta version, it has also been published to [PyPI](https://pypi.org/project/trakt-scrobbler/), so simply running `pipx upgrade --pip-args='--pre' trakt-scrobbler` _should_ do the trick. 
Let me know if that works, and I'll update the release description. Thanks for reporting the issue.

**Comment by Hillgrove** [comment]
something happened alright.

```
  Overwriting file C:\Users\Hillgrove\.local\bin\trakts.exe with C:\Users\Hillgrove\.local\pipx\venvs\trakt-scrobbler\Scripts\trakts.exe
←[?25hTraceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hillgrove\AppData\Roaming\Python\Python39\Scripts\pipx.exe\__main__.py", line 7, in <module>
  File "C:\Users\Hillgrove\AppData\Roaming\Python\Python39\site-packages\pipx\main.py", line 609, in cli
    return run_pipx_command(parsed_pipx_args)
  File "C:\Users\Hillgrove\AppData\Roaming\Python\Python39\site-packages\pipx\main.py", line 186, in run_pipx_command
    return commands.upgrade(
  File "C:\Users\Hillgrove\AppData\Roaming\Python\Python39\site-packages\pipx\commands\upgrade.py", line 69, in upgrade
    expose_apps_globally(
  File "C:\Users\Hillgrove\AppData\Roaming\Python\Python39\site-packages\pipx\commands\common.py", line 27, in expose_apps_globally
    _copy_package_apps(local_bin_dir, app_paths, suffix=suffix)
  File "C:\Users\Hillgrove\AppData\Roaming\Python\Python39\site-packages\pipx\commands\common.py", line 67, in _copy_package_apps
    dest.unlink()
  File "c:\program files\python39\lib\pathlib.py", line 1343, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Hillgrove\\.local\\bin\\trakts.exe'
```

**Comment by iamkroot** [comment]
You need to kill trakts first. `trakts stop`

**Comment by iamkroot** [comment]
@Hillgrove did it work?

**Comment by iamkroot** [comment]
Closing due to inactivity

**Comment by Hillgrove** [comment]
sorry for the delay.. I had some personal issues I had to deal with :/

I think my Python install is bugged.

When I try to run the

`trakts stop`

command I get this error command

https://imgur.com/a/mIBWRfi

**Comment by iamkroot** [comment]
I thought it got fixed since some other folks were able to install it. 
But it seems there's a deeper issue here. The error is from `urllib3`, which is a dependency of this app. Using the `--force` option really doesn't do what we want. The first command you ran probably upgraded the app to beta, but not the dependencies, which has caused everything to break. 
Instead, you'll have to stop the scrobbler manually: 
1. Open up task manager (I think Ctrl+Shift+Esc should do the trick, not sure)
2. Open the "More Details" view
3. Open the Details tab
4. Look for `trakts.exe`
5. Right click it, end process.

Here's a guide with pics: https://winaero.com/kill-process-windows-10/

Next, you should remove the app and reinstall (data will be safe):
1. `pipx uninstall trakt-scrobbler`
2. `pipx install trakt-scrobbler==1.3.0b2` (turns out just specifying the exact version is enough, no need to do all the `--force` stuff, will update the Releases page)
3. `trakts start`
4. `trakts status` to make sure everything is fine

That should hopefully fix this.

**Comment by Hillgrove** [comment]
everything seems to be running in order :)

thanks again for the very helpful (and patient) support.

**Comment by iamkroot** [comment]
Great! Thanks for creating the issue in the first place - I got a chance to fix the incorrect steps :)
