### ISSUE TITLE
[Installation] ERROR - Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by KMLAgency** [iamkroot/trakt-scrobbler#156]
### System Info
* Operating system and version: Opensuse Leap 15.3, Kernel 5.3.18-59.24, KDE plasma 5
* Media Player and version: VLC v3.0.13
* Python version: 3.6
* Pipx version: 0.16.4

### Description
Error while installing...

### Command line output

```
pipx install trakt-scrobbler
Fatal error from pip prevented installation. Full pip output in file:
    /home/loky/.local/pipx/logs/cmd_2021-10-06_21.38.14_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement trakt-scrobbler (from versions: none)
    ERROR: No matching distribution found for trakt-scrobbler

Error installing trakt-scrobbler.
```

### Log file

<details>
  <summary>Click to see log contents</summary>  
<p>

```
127.3ms (setup:715): 2021-10-06 21:38:14
   127.4ms (setup:716): /home/loky/.local/bin/pipx install trakt-scrobbler
   127.5ms (setup:717): pipx version is 0.16.4
   127.5ms (setup:718): Default python interpreter is '/usr/bin/python3'
   127.9ms (package_name_from_spec:323): Determined package name: trakt-scrobbler
   128.0ms (package_name_from_spec:324): Package name determined in 0.0s
   128.6ms (run_subprocess:135): running /usr/bin/python3 -m venv --without-pip /home/loky/.local/pipx/venvs/trakt-scrobbler
   174.4ms (run_subprocess:148): stdout:
   174.5ms (run_subprocess:150): stderr:
   174.5ms (run_subprocess:151): returncode: 0
   175.1ms (run_subprocess:135): running /home/loky/.local/pipx/venvs/trakt-scrobbler/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
   189.8ms (run_subprocess:148): stdout: /home/loky/.local/pipx/venvs/trakt-scrobbler/lib/python3.6/site-packages
   190.0ms (run_subprocess:151): returncode: 0
   190.4ms (run_subprocess:135): running /home/loky/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
   206.0ms (run_subprocess:148): stdout: /home/loky/.local/pipx/shared/lib/python3.6/site-packages
   206.1ms (run_subprocess:151): returncode: 0
   206.6ms (run_subprocess:135): running /home/loky/.local/pipx/venvs/trakt-scrobbler/bin/python --version
   209.0ms (run_subprocess:148): stdout: Python 3.6.13
   209.1ms (run_subprocess:150): stderr:
   209.1ms (run_subprocess:151): returncode: 0
   210.2ms (_parsed_package_to_package_or_url:128): cleaned package spec: trakt-scrobbler
   210.9ms (run_subprocess:135): running /home/loky/.local/pipx/venvs/trakt-scrobbler/bin/python -m pip install trakt-scrobbler
   952.1ms (run_subprocess:151): returncode: 1
   952.4ms (subprocess_post_check_handle_pip_error:297): '/home/loky/.local/pipx/venvs/trakt-scrobbler/bin/python -m pip install trakt-scrobbler' failed
   952.8ms (subprocess_post_check_handle_pip_error:315): Fatal error from pip prevented installation. Full pip output in file:
    /home/loky/.local/pipx/logs/cmd_2021-10-06_21.38.14_pip_errors.log
   955.0ms (rmdir:43): removing directory /home/loky/.local/pipx/venvs/trakt-scrobbler
   955.5ms (cli:768): PipxError: Error installing trakt-scrobbler.
Traceback (most recent call last):
  File "/home/loky/.local/lib/python3.6/site-packages/pipx/main.py", line 765, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/loky/.local/lib/python3.6/site-packages/pipx/main.py", line 204, in run_pipx_command
    suffix=args.suffix,
  File "/home/loky/.local/lib/python3.6/site-packages/pipx/commands/install.py", line 67, in install
    suffix=suffix,
  File "/home/loky/.local/lib/python3.6/site-packages/pipx/venv.py", line 241, in install_package
    f"Error installing {full_package_description(package_name, package_or_url)}."
pipx.util.PipxError: Error installing trakt-scrobbler.
   956.1ms (cli:776): pipx finished.
```
</p>
</details>

**Comment by MetaStazz** [comment]
I update python to 3.8.12 and still not working !!

### Command line output


```
⚠️  All pipx binary directories have been added to PATH. If you are sure you want to proceed, try again with the '--force' flag.

Otherwise pipx is ready to go! ✨ 🌟 ✨
loky@stellaris:~> pipx install trakt-scrobbler
Fatal error from pip prevented installation. Full pip output in file:
    /home/loky/.local/pipx/logs/cmd_2021-10-07_11.17.40_pip_errors.log

Error installing trakt-scrobbler.

```

### Log file





<details>
  <summary>Click to see log contents</summary>  
<p>

```
    96.0ms (setup:715): 2021-10-07 11:17:40
    96.1ms (setup:716): /home/loky/.local/bin/pipx install trakt-scrobbler
    96.2ms (setup:717): pipx version is 0.16.4
    96.2ms (setup:718): Default python interpreter is '/usr/bin/python3'
    96.6ms (package_name_from_spec:323): Determined package name: trakt-scrobbler
    96.6ms (package_name_from_spec:324): Package name determined in 0.0s
    97.2ms (run_subprocess:135): running /usr/bin/python3 -m venv --without-pip /home/loky/.local/pipx/venvs/trakt-scrobbler
   137.5ms (run_subprocess:148): stdout:
   137.6ms (run_subprocess:150): stderr:
   137.7ms (run_subprocess:151): returncode: 0
   138.2ms (run_subprocess:135): running /home/loky/.local/pipx/venvs/trakt-scrobbler/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
   151.5ms (run_subprocess:148): stdout: /home/loky/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages
   151.7ms (run_subprocess:151): returncode: 0
   152.0ms (run_subprocess:135): running /home/loky/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
   165.6ms (run_subprocess:148): stdout: /home/loky/.local/pipx/shared/lib/python3.8/site-packages
   165.7ms (run_subprocess:151): returncode: 0
   166.2ms (run_subprocess:135): running /home/loky/.local/pipx/venvs/trakt-scrobbler/bin/python --version
   168.3ms (run_subprocess:148): stdout: Python 3.8.12
   168.4ms (run_subprocess:150): stderr:
   168.4ms (run_subprocess:151): returncode: 0
   169.2ms (_parsed_package_to_package_or_url:128): cleaned package spec: trakt-scrobbler
   169.8ms (run_subprocess:135): running /home/loky/.local/pipx/venvs/trakt-scrobbler/bin/python -m pip install trakt-scrobbler
   190.6ms (run_subprocess:151): returncode: 1
   191.0ms (subprocess_post_check_handle_pip_error:297): '/home/loky/.local/pipx/venvs/trakt-scrobbler/bin/python -m pip install trakt-scrobbler' failed
   191.2ms (subprocess_post_check_handle_pip_error:314): Fatal error from pip prevented installation. Full pip output in file:
    /home/loky/.local/pipx/logs/cmd_2021-10-07_11.17.40_pip_errors.log
   193.0ms (rmdir:43): removing directory /home/loky/.local/pipx/venvs/trakt-scrobbler
   193.4ms (cli:768): PipxError: Error installing trakt-scrobbler.
Traceback (most recent call last):
  File "/home/loky/.local/lib/python3.8/site-packages/pipx/main.py", line 765, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/loky/.local/lib/python3.8/site-packages/pipx/main.py", line 193, in run_pipx_command
    return commands.install(
  File "/home/loky/.local/lib/python3.8/site-packages/pipx/commands/install.py", line 60, in install
    venv.install_package(
  File "/home/loky/.local/lib/python3.8/site-packages/pipx/venv.py", line 240, in install_package
    raise PipxError(
pipx.util.PipxError: Error installing trakt-scrobbler.
   193.9ms (cli:776): pipx finished.
```
</p>
</details>

**Comment by iamkroot** [comment]
Closing due to inactivity.
