### ISSUE TITLE
[Request]Can MPV get_property add media-title choice.

### ISSUE THREAD

**Issue by AlickH** [iamkroot/trakt-scrobbler#169]
Sometimes the url stream link did not contain the file name, but mpv can set the media title through m3u list or by `--force-media-title` command.

**Comment by iamkroot** [comment]
Yeah, we probably could do it instead of reading the path. 
But the issue is deciding between the two. I've found that many a time, the Media Title does _not_ contain meaningful information (eg: Only the episode title, but no show name). We can't simply stop using the path for extracting info and switch to title.
And in cases where both contain partial info, one of which is wrong (eg: Weird url from which we somehow extracted some gibberish, but valid info - remember, this is all powered by regexes at the core), how do we decide what to use?

This was my original motivation for choosing path instead of title, since that is something that the user could control (for any media player). But now that we have streaming support from the web, this assumption doesn't hold true. However, I'm not sure on how to fix this without requiring a lot of manual intervention.

Some possible solutions-
1. (Easy) Prefer Title instead of path when the media is being streamed from a url. This will again run into the same issue of the title property not having enough info very frequently.
2. (Hard) Do media info extraction on both, the path and title. Then, come up with some scheme to _merge_ the results from both.
    1. What to do with conflicts? Maybe we can have it set to prefer path over title, or vice versa.
    2. Even better, this preference could be configured per whitelist entry. Since we would usually like to use the url/path for some good media sources, and the title property for the cases when the url isn't helping.

**Comment by AlickH** [comment]
Maybe could combine this with whitelist to choose which path or url to use path or title, or let user to write it to config file to choose title or path, or popup a dialog box to choose which to use when there are two options.

**Comment by iamkroot** [comment]
> popup a dialog box to choose which to use when there are two options.

That is way too intrusive. I would like the scrobbler to not require manual intervention, especially on every file.

> let user to write it to config file to choose title or path

Yeah, this seems feasible. Will try implementing it when I get some free time.

**Comment by umop3plsdn** [comment]
I came to ask about this as well. Apparently it's using filename so when i'm streaming some content it only picks up filename from the IPC socket for scrobble instead of media-title

**Comment by iamkroot** [comment]
As stated above, my main worry with this is making the configuration too manual. But now that #214 has been implemented, we have a pretty powerful way of specifying how to remap raw media info.
Currently, the feature only works on info extracted from file paths, but it should be relatively easy to extend that to file title retrieved from mpv. Will try to work on this soon.

**Comment by iamkroot** [comment]
I have implemented an initial version of this feature in the [title-extract](https://github.com/iamkroot/trakt-scrobbler/tree/title-extract) branch.

If the title provided by the media player is present in `fileinfo.title_whitelist` sequence, it will be used to extract info instead of file path. There is currently no way to merge the infos extracted from title and path individually.

Install from branch:
1. Stop the scrobbler with `trakts stop`
2. Run `pipx install --force --pip-args='--force-reinstall' git+https://github.com/iamkroot/trakt-scrobbler.git@title-extract`
3. Start scrobbler with `trakts start`

Configuration: `trakts config set --add fileinfo.title_whitelist "Some Name"`

Please give it a try and let me know if everything is working as expected.

**Comment by iamkroot** [comment]
@AlickH @umop3plsdn would appreciate your feedback on the design!

**Comment by umop3plsdn** [comment]
Sorry didn't see this until today. So switch to the title-extract branch and what do i need to run or change to get it going

**Comment by umop3plsdn** [comment]
2023-01-12 09:12:32,067 - WARNING - scrobbler - trakt_interface - Invalid trakt id for 1649804033
2023-01-12 09:12:32,067 - ERROR - scrobbler - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/da5id/.local/pipx/venvs/trakt-scrobbler/lib/python3.10/site-packages/trakt_scrobbler/scrobbler.py", line 36, in run
    self.scrobble(verb, data)
  File "/home/da5id/.local/pipx/venvs/trakt-scrobbler/lib/python3.10/site-packages/trakt_scrobbler/scrobbler.py", line 78, in scrobble
    resp = trakt.scrobble(verb, **data)
  File "/home/da5id/.local/pipx/venvs/trakt-scrobbler/lib/python3.10/site-packages/trakt_scrobbler/trakt_interface.py", line 48, in wrapped
    verb, params = next(coro)
StopIteration

**Comment by umop3plsdn** [comment]
also its still picking up the same thing:
 trakts test mpv
Testing connection with mpv.
Please ensure that mpv is playing some media.
 - Connected
 - Got info
Playing 1649804033 S10E07 at 55.88%

**Comment by umop3plsdn** [comment]
echo '{"command": ["get_property", "media-title"]}' |socat - /tmp/mpvsocket
{"data":"bleach-episode-7-dub","request_id":0,"error":"success"}

**Comment by iamkroot** [comment]
Sorry, that was a small bug in the code. I've pushed a fix. Please re-install using the instructions above.

**Comment by umop3plsdn** [comment]
alright reinstalled and it looks like its still pulling off the same location. for the record i double checked that the changes you pushed out were actually present in /home/da5id/.local/pipx/venvs/trakt-scrobbler/bin/trakts just to double check since it was the same result. Also, to help i tried a youtube vid randomly https://www.youtube.com/watch?v=djA0fYk65yI 
trakt-scrobbler on  title-extract via 🐍 v3.10.9
➜ echo '{"command": ["get_property", "media-title"]}' |socat - /tmp/mpvsocket
{"data":"Destiny Reacts To Boyinaband Allegations","request_id":0,"error":"success"}

➜ trakts test mpv
Testing connection with mpv.
Please ensure that mpv is playing some media.
 - Connected
 - Got info
Playing watch at 1.82%

**Comment by iamkroot** [comment]
Are you sure you've added that title to `fileinfo.title_whitelist` config as mentioned in the steps above? Please check the scrobbler logs too.

**Comment by umop3plsdn** [comment]
omg i didn't see that part i am so sorry! i can't believe i missed that entirely wow. Even the install method is easier than how i was doing it locally lol. So would it be trakts config set --add fileinfo.title_whitelist "media-title"?

**Comment by umop3plsdn** [comment]
![2023-01-13-10:04:34](https://user-images.githubusercontent.com/696094/212351867-40c5bd75-257b-4a50-8a2e-7f7812b9f7b8.png)

**Comment by umop3plsdn** [comment]
I did restart after for the record and got the same result lol

**Comment by umop3plsdn** [comment]
thank you for clarifying! I almost thought it was that but then I second guessed and thought it was the field of choosing. 
trakts test mpv
Testing connection with mpv.
Please ensure that mpv is playing some media.
 - Connected
 - Got info
Playing 03f7ff340442485a8dbcbd809d2006da S85E445 at 2.15%
[da5id@tesla] ➜ ~ echo '{"command": ["get_property", "media-title"]}' |socat - /tmp/mpvsocket| jq
{
  "data": "vinland-saga-episode-17-dub",
  "request_id": 0,
  "error": "success"
}

**Comment by umop3plsdn** [comment]
Sweet it works on bleach!

**Comment by iamkroot** [comment]
Ah thanks for catching that. Maybe we should do case-insensitive comparison for matching titles.
