### ISSUE TITLE
[BUG] MPVWinMon' object has no attribute '_transact_read_buf

### ISSUE THREAD

**Issue by NatsuDzn** [iamkroot/trakt-scrobbler#179]
An error occurs when trakts try to monitor mpv 

**Desktop (please complete the following information):**
 - OS and Version: Windows 10 21H1
 - Python Version: Python 3.10.2
 - Player and Version: mpv-x86_64-20220213-git-bc9805c (mpv 0.34.0-198-gbc9805c71a)

**To Reproduce**

Open any file and the error will pop up
I don't know if this can help but I have updated mpv then trakts 

Since this error I always need to launch ```trakts start -r``` to trigger the start, but there is always the same error

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```
2022-02-26 22:46:30,949 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2022-02-26 22:46:31,131 - INFO - MainThread - scrobbler - Started scrobbler thread.
2022-02-26 22:46:31,144 - INFO - MainThread - monitor - Started monitor for mpv
2022-02-26 22:46:31,151 - ERROR - mpv - __init__ - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\admin\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\__init__.py", line 42, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\admin\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 80, in run
    self.conn_loop()
  File "C:\Users\admin\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 355, in conn_loop
    data = self._call(self._transact, write_data)
  File "C:\Users\admin\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 286, in _call
    return method(*args)
  File "C:\Users\admin\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 267, in _transact
    read_buf = self._transact_read_buf
AttributeError: 'MPVWinMon' object has no attribute '_transact_read_buf'
```
</p>
</details>

**Comment by iamkroot** [comment]
Thanks for the detailed bug report! This was a bug introduced in the latest version. Will release a bugfix version for it.
