### ISSUE TITLE
[BUG] Error in character encoding guess on mpv.conf

### ISSUE THREAD

**Issue by dyphire** [iamkroot/trakt-scrobbler#183]
**Describe the bug**

The file  of mpv.conf is encoded in UTF-8, but it is incorrectly treated as GBK encoding

**Desktop (please complete the following information):**
 - OS and Version: Windows11
 - Python Version: 3.10.2
 - Player and Version: mpv-0.34.1-git

**To Reproduce**

N/A

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
2022-03-07 23:02:32,020 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
Traceback (most recent call last):
  File "E:\Tools\Scoop\apps\python\current\lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 82, in __new__
    cls.config = cls.autoload_cfg()
  File "E:\Tools\Scoop\apps\python\current\lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 112, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "E:\Tools\Scoop\apps\python\current\lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 71, in read_player_cfg
    mpv_conf.read_string("[root]\n" + conf_path.read_text())
  File "E:\Tools\Scoop\apps\python\current\lib\pathlib.py", line 1133, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9a in position 60: illegal multibyte sequence
2022-03-07 23:02:32,026 - WARNING - MainThread - main - Could not start monitor for mpv
```
</p>
</details>

**Comment by dyphire** [comment]
May be relevant: https://github.com/rkern/line_profiler/issues/37, I think we should use UTF-8 as default decode.
