### ISSUE TITLE
[BUG] Can't initialise

### ISSUE THREAD

**Issue by lhupitr** [iamkroot/trakt-scrobbler#204]
**Describe the bug**

Running `trakts init` after installation fails with notification:

> Unhandled exception
No module named 'urlmatch'

**Desktop (please complete the following information):**
 - Arch Linux
 - Python 3.10.6

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
2022-08-20 18:14:04,217 - ERROR - MainThread - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/usr/bin/trakts", line 33, in <module>
    sys.exit(load_entry_point('trakt-scrobbler==1.5.0', 'console_scripts', 'trakts')())
  File "/usr/bin/trakts", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/trakt_scrobbler/console.py", line 18, in <module>
    from trakt_scrobbler.commands.whitelist import WhitelistCommand
  File "/usr/lib/python3.10/site-packages/trakt_scrobbler/commands/whitelist.py", line 4, in <module>
    from urlmatch.urlmatch import BadMatchPattern, urlmatch
ModuleNotFoundError: No module named 'urlmatch'
```
</p>
</details>

**Comment by iamkroot** [comment]
@ahmubashshir?

**Comment by ahmubashshir** [comment]
@lhupitr did you install from aur?

**Comment by lhupitr** [comment]
Yes, I installed through the aur

**Comment by ahmubashshir** [comment]
Try reinstalling. AFAIK, both trakt-scrobbler and trakt-scrobbler-git has all dependencies added in the pkgbuild.

**Comment by lhupitr** [comment]
I had to rebuild and reinstall python-urlmatch python-guessit and python-babelfish, working fine now.

**Comment by ahmubashshir** [comment]
@iamkroot this can be closed...
