### ISSUE TITLE
No scrobble after Trakt 12-11-2022 DB Crash due to corrupted watched_backlog.json file

### ISSUE THREAD

**Issue by yeyogrande** [iamkroot/trakt-scrobbler#239]
To RECAP: for any users who are experiencing NO scrobble issues after Trakt December 21, 2022 crash. I had a corrupted watched_backlog.json file. It was creating many multiple episode instances of episodes in my trakt history. And, it was also causing the scrobbler program to crash. I moved the watched_backlog.json file and did a trakts start --restart and it was fixed. For recovery of missed trakt history read the rest of this post.

No scrobbles since Dec 11 2022 Trakt DB crash. No smplayer, vlc, mpv scrobble anymore. Tried commands auth init etc. Tried re-installing current newest release & re configed it. No scrobble in players. Tried reinstalling newest beta client as of Jan 2023. Tried logging out back in trakt. Tried all new token and auth commands all to no avail. No scrobbling in smplayer, mpv or vlc. I cant be the only one experiencing this? Am I? the only one?. Thank You and LOVE this app, it was truly heaven sent!! Never a problem until THE BIG CRASH of XMAS 2022 at Trakt. Please advise.

Lubuntu 20.04
Newest versions of everything updated through commandline sudo apt update & upgrade as of Jan 10

**Comment by boris377** [comment]
Same story here. No scrobble.

**Comment by iamkroot** [comment]
@boris377 have you tried the instructions in #234?

**Comment by yeyogrande** [comment]
Thank you for timely reply iamkroot ...you the man :)  [that i wish i was ;) ]
 Starting troubleshooting again right now following bugtraq #234:
Closed all trakt web page instances. I Go to https://trakt.tv/oauth/authorized_applications 
X REVOKE ACCESS (4th Try since trakt DB crash !)
trakts -V
Trakts version 1.6.1-beta1
:~$ trakts auth --force
Forcing trakt authentication
Open https://trakt.tv/activate in your browser and enter this code: xxxxxx
Opening in existing browser session.
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
App authorized successfully.
Token valid until 04/06/23
trakts start --restart
The scrobbler is running
Monitored players: mpv, plex, smplayer@mpv, vlc
No activity yet.
I googled the libva errors above as I never experienced them b4 and I am OC type as far as unix errors. Looks like (intel-media-va-driver:amd64) prob. will sort out later.
Tried to scrobble a show. no scrobble. Logout and login Trakt website. Try again. No scrobble.
trakts status
The scrobbler is running
Monitored players: mpv, plex, smplayer@mpv, vlc
No activity yet

trakts log open:
Log file is located at: "/myhomedir/.local/share/trakt-scrobbler/trakt_scrobbler.log"
In case this command doesn't work, manually open the log file from the path.
mybox:~$ Warning: program returned non-zero exit code #256
Opening "/myhome/.local/share/trakt-scrobbler/trakt_scrobbler.log" with FeatherPad  (text/x-log)
Icon theme "elementary" not found.

Here is a piece of log that does not look good, i.e. not being added to history:

2023-01-04 16:36:31,757 - ERROR - backlog_cleaner - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/stax/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/backlog_cleaner.py", line 50, in clear
    if trakt.add_to_history(**item):
  File "/home/stax/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/trakt_interface.py", line 148, in add_to_history
    history = prepare_history_data(watched_at, media_info)
  File "/home/stax/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/trakt_interface.py", line 139, in prepare_history_data
    {'number': media_info['season'], 'episodes': [
KeyError: 'season'
2023-01-06 12:12:41,020 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2023-01-06 12:12:41,229 - INFO - notify_loop - notifier - Starting notif loop
2023-01-06 12:12:41,229 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2023-01-06 12:12:41,231 - INFO - MainThread - trakt_auth - Access token not found. Initiating device authentication.
2023-01-06 12:12:41,563 - INFO - MainThread - trakt_auth - Verification URL: https://trakt.tv/activate
2023-01-06 12:12:41,564 - INFO - MainThread - trakt_auth - User Code: 9344835A
2023-01-06 12:12:52,901 - WARNING - MainThread - utils - Request failed
2023-01-06 12:12:52,902 - DEBUG - MainThread - utils - Request: post {'url': 'https://api.trakt.tv/oauth/device/token', 'headers': {'Content-Type': 'application/json'}, 'json': {'code': '145a6deea008f3c08f3336b6a7e9689d1f8a16433864b8015e9f9d22123a1e44', 'client_id': 'ab0133a2365b2c64d70fd2adf3c7e775a4131471b56340933335af1b94785a3a', 'client_secret': 'b574acd5857310fcdc1e195c5953795fc61a1d89d69fec1649624d54cb666222'}}
2023-01-06 12:12:52,902 - DEBUG - MainThread - utils - Response: <Response [400]> 
2023-01-06 12:12:52,902 - DEBUG - MainThread - trakt_auth - Waiting for user to authorize the app.
2023-01-06 12:12:57,967 - WARNING - MainThread - utils - Request failed
2023-01-06 12:12:57,967 - DEBUG - MainThread - utils - Request: post {'url': 'https://api.trakt.tv/oauth/device/token', 'headers': {'Content-Type': 'application/json'}, 'json': {'code': '145a6deea008f3c08f3336b6a7e9689d1f8a16433864b8015e9f9d22123a1e44', 'client_id': 'ab0133a2365b2c64d70fd2adf3c7e775a4131471b56340933335af1b94785a3a', 'client_secret': 'b574acd5857310fcdc1e195c5953795fc61a1d89d69fec1649624d54cb666222'}}
2023-01-06 12:12:57,967 - DEBUG - MainThread - utils - Response: <Response [400]> 
2023-01-06 12:12:57,967 - DEBUG - MainThread - trakt_auth - Waiting for user to authorize the app.
2023-01-06 12:13:03,045 - WARNING - MainThread - utils - Request failed
2023-01-06 12:13:03,045 - DEBUG - MainThread - utils - Request: post {'url': 'https://api.trakt.tv/oauth/device/token', 'headers': {'Content-Type': 'application/json'}, 'json': {'code': '145a6deea008f3c08f3336b6a7e9689d1f8a16433864b8015e9f9d22123a1e44', 'client_id': 'ab0133a2365b2c64d70fd2adf3c7e775a4131471b56340933335af1b94785a3a', 'client_secret': 'b574acd5857310fcdc1e195c5953795fc61a1d89d69fec1649624d54cb666222'}}
2023-01-06 12:13:03,046 - DEBUG - MainThread - utils - Response: <Response [400]> 
2023-01-06 12:13:03,046 - DEBUG - MainThread - trakt_auth - Waiting for user to authorize the app.
2023-01-06 12:13:08,137 - INFO - MainThread - trakt_auth - App authorized successfully.
2023-01-06 12:15:57,408 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2023-01-06 12:15:57,437 - INFO - notify_loop - notifier - Starting notif loop
2023-01-06 12:15:57,438 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2023-01-06 12:16:00,742 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 0, 'progress': 99.96, 'media_info': {'type': 'episode', 'title': 'The Young Pope', 'season': 1, 'episode': 5}, 'updated_at': 1670816993.0620918}
2023-01-06 12:16:01,026 - INFO - MainThread - backlog_cleaner - Successfully added media to history.
2023-01-06 12:16:01,026 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 0, 'progress': 99.96, 'media_info': {'type': 'episode', 'title': 'The Young Pope', 'season': 1, 'episode': 5}, 'updated_at': 1670816993.0646179}
2023-01-06 12:16:01,178 - INFO - MainThread - backlog_cleaner - Successfully added media to history.
2023-01-06 12:16:01,179 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 0, 'progress': 100.0, 'media_info': {'type': 'episode', 'title': 'The Young Pope', 'season': 1, 'episode': 1}, 'updated_at': 1670822083.8170059}
MOST OF LOG looks like above last few lines which I take it is proper correct?

you said in your response to upload trakt_backlog.json: I dont have that file verbatim
~/.local/share/trakt-scrobbler$ ls
plex_token.txt    trakt_scrobbler.log    trakt_scrobbler.log.2  trakt_scrobbler.log.4  trakt_token.json
trakt_cache.json  trakt_scrobbler.log.1  trakt_scrobbler.log.3  trakt_scrobbler.log.5  watched_backlog.json
So  I took a look at :
mybox:~/.local/share/trakt-scrobbler$ nano watched_backlog.json  
(is this the file you are refering to?
this file watched_backlog.json looks pretty good do you want me to grep for something ? 

Thanks again brother. Lemme know if I can upload anything else. Peace out.

**Comment by yeyogrande** [comment]
Regarding the error you see in backlog clear output, I suspect some file has been edited manually. The "season" number is missing from one of the scrobbled episodes present in your backlog, which is not supposed to happen unless the backlog is edited by hand. 

Forgot to respond to this in my above response. I have not edited these files nor had I looked at them as I was ignorant of them since I had been running your scrobbler sucessfully thru so man versions. I.E. no problems no looky at the loggies. Thanks.

**Comment by yeyogrande** [comment]
iamkroot,
Let me know what you find and if nothing strikes you shall we assume this is a bug on the trakt side. I must say my past with these things gives me this gut feeling. Lets review: Your scrobbler is running great for me since installation. Trakt has a big DB crash Dec 11 2022, then it stops working. WTF.

I see my Trakt watched history is restored up to Dec 21 but what is odd is that there a lot of multiple entries in a row of the same show episode, whats this about? I am tempted to create a new Trakt account and try that. But doing so I would lose prior watched history which would suck ass. Is there a method to transfer history from old account to a new account on Trakt. Please advise. Until Later, Your appreciative user, YG.

**Comment by yeyogrande** [comment]
Tried a fresh Trakt account. Still no scrobble. :(

**Comment by iamkroot** [comment]
>  This file: watched_backlog.json looks pretty good do you want me to grep for something?

Would be helpful if you could paste a redacted version of it here (removing titles).

Next steps:
1. Read what `watched_backlog.json` is used for - [here](https://github.com/iamkroot/trakt-scrobbler/wiki/FAQs#what-happens-when-there-is-no-internet-connection). In short, it stored all the failed scrobbles when the Trakt API was down. Now we try to sync it back to Trakt, but one (or more) of those scrobbles is corrupted _for some reason_ and our program crashes midway. Next time we start, we again try to sync and fail again. This is why you are seeing duplicate entries on your Trakt history.
2. Manually mark the scrobbles from `watched_backlog.json` on Trakt using their "Add to History" button on the website. For the duplicated scrobbles, remove them from Trakt. Then once you are satisfied that your entire history is present on Trakt correctly, delete the `watched_backlog.json` file.
3. After restarting, your scrobbler *should* work normally.

(No need to create a second Trakt account)

**Comment by yeyogrande** [comment]
[watched_backlog.txt](https://github.com/iamkroot/trakt-scrobbler/files/10369199/watched_backlog.txt)

**Comment by yeyogrande** [comment]
Sounds promising. How about I just mv the backlog.json file and restart trakts? Can I deal with history later by switching the newly created backlog.json out for my mv'ed file and then reverse the process? I would like to see a notification that my scrobbling is working? Thanks for all iamkroot. YG.

**Comment by yeyogrande** [comment]
think i answered some of my own questions above. did a wc -l on backlog finding date with date -d and doing a piece at a time. will report sucess or failure back soon

**Comment by yeyogrande** [comment]
Thanks again for keeping me from having to RTFM.
