### ISSUE TITLE
[BUG] macOS installation fails on main.py step

### ISSUE THREAD

**Issue by kevinji** [iamkroot/trakt-scrobbler#26]
**Describe the bug**
The macOS installation steps fail on the `pipenv run python main.py` step (which should be `pipenv run python scripts/main.py`, and is missing a step `cp config.toml ~/Library/Preferences/trakt-scrobbler/config.toml`):

```
❯ pipenv run python trakt_scrobbler/main.py
dbus[1044]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
Traceback (most recent call last):
  File "trakt_scrobbler/main.py", line 12, in <module>
    from scrobbler import Scrobbler
  File "/Users/kevinji/Documents/GitHub/trakt-scrobbler/trakt_scrobbler/scrobbler.py", line 3, in <module>
    from notifier import notify
  File "/Users/kevinji/Documents/GitHub/trakt-scrobbler/trakt_scrobbler/notifier.py", line 8, in <module>
    notify2.init(APP_NAME)
  File "/Users/kevinji/.local/share/virtualenvs/trakt-scrobbler-WfXl7Y8L/lib/python3.7/site-packages/notify2.py", line 100, in init
    bus = dbus.SessionBus(mainloop=mainloop)
  File "/Users/kevinji/.local/share/virtualenvs/trakt-scrobbler-WfXl7Y8L/lib/python3.7/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/Users/kevinji/.local/share/virtualenvs/trakt-scrobbler-WfXl7Y8L/lib/python3.7/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/Users/kevinji/.local/share/virtualenvs/trakt-scrobbler-WfXl7Y8L/lib/python3.7/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoMemory: Not enough memory
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version: 3.7.4
 - Player: N/A
 - Player Version: N/A

**To Reproduce**
Follow the macOS steps to the `pipenv run python main.py` step. I've installed `dbus` with Homebrew and also ran `brew services start dbus`, and rebooted my machine.

**Log file**
N/A

**Comment by iamkroot** [comment]
Thanks for the info on the install steps, I'll fix the README.

Regarding the dbus error, see if running these help:
```
launchctl load -w /Library/LaunchDaemons/org.freedesktop.dbus-system.plist
launchctl load -w /Library/LaunchAgents/org.freedesktop.dbus-session.plist 
launchctl start org.freedesktop.dbus-system
launchctl start org.freedesktop.dbus-session
```

**Comment by iamkroot** [comment]
Hey @kevinji I've updated the MacOS notification in PR #29 . Could you pull that code and check to see if its working?
