### ISSUE TITLE
[BUG] Python 3.12 uncaught exceptions

### ISSUE THREAD

**Issue by Sp3EdeR** [iamkroot/trakt-scrobbler#268]
The log contains many uncaught exceptions about trying to spawn threads during thread shutdown, including from the uncaught exception handler.

A clear and concise description of what the bug/error is.

**Desktop (please complete the following information):**
 - OS and Version: Windows 11
 - Python Version: 3.12
 - Player and Version: MPC-HC 2.1.3

Just start playing anything, the exceptions will happen instantly.

1. Open any file
2. Play
3. See the error in log file

**Log file extract**

<details><summary>Click to see log contents</summary> 
<p>

```
2023-12-24 21:43:19,644 - ERROR - scrobbler - __init__ - Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files (x86)\Fejlesztői Eszközök\Python\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\scrobbler.py", line 36, in run
    self.scrobble(verb, data)
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\scrobbler.py", line 80, in scrobble
    self.handle_successful_scrobble(verb, data, resp)
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\scrobbler.py", line 72, in handle_successful_scrobble
    notify(msg, category=f"scrobble.{category}", actions=(action,))
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\notifier.py", line 126, in notify
    toaster.show_toast(title, body, duration=timeout, threaded=True)
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\win10toast\__init__.py", line 134, in show_toast
    self._thread.start()
  File "C:\Program Files (x86)\Fejlesztői Eszközök\Python\Lib\threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
2023-12-24 21:43:19,645 - ERROR - scrobbler - __init__ - Exception while notifying user.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Fejlesztői Eszközök\Python\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\scrobbler.py", line 36, in run
    self.scrobble(verb, data)
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\scrobbler.py", line 80, in scrobble
    self.handle_successful_scrobble(verb, data, resp)
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\scrobbler.py", line 72, in handle_successful_scrobble
    notify(msg, category=f"scrobble.{category}", actions=(action,))
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\notifier.py", line 126, in notify
    toaster.show_toast(title, body, duration=timeout, threaded=True)
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\win10toast\__init__.py", line 134, in show_toast
    self._thread.start()
  File "C:\Program Files (x86)\Fejlesztői Eszközök\Python\Lib\threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\__init__.py", line 21, in error_logger
    notify(f"Check log file.\n{exc_info[1]}", "Unhandled Exception",
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\notifier.py", line 126, in notify
    toaster.show_toast(title, body, duration=timeout, threaded=True)
  File "C:\ProgramData\pipx\venvs\trakt-scrobbler\Lib\site-packages\win10toast\__init__.py", line 134, in show_toast
    self._thread.start()
  File "C:\Program Files (x86)\Fejlesztői Eszközök\Python\Lib\threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
```
</p>
</details>

**Comment by iamkroot** [comment]
Hmm, this is a weird one- I'm not sure where the "Interpreter Shutdown" comes from- all we do is start a timer 😓 Will need some time to debug
