### ISSUE TITLE
[BUG] Issue when starting trakts

### ISSUE THREAD

**Issue by flameshikari** [iamkroot/trakt-scrobbler#269]
**System Info**
 - OS and Version: Windows 11 Pro 23H2
 - Python Version: 3.12.1
 - Player and Version: MPC-BE x64 1.6.11

**Description**

![2023-12-30_21-58-44_650](https://github.com/iamkroot/trakt-scrobbler/assets/17804422/4cddf392-4590-462b-aae2-3f0476e81020)

![2023-12-30_21-59-00_651](https://github.com/iamkroot/trakt-scrobbler/assets/17804422/90315aee-6c02-453a-a614-17586114b00a)

**To Reproduce**

1. Install `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git@master`
2. Execute `trakts run`

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```
2023-12-30 21:51:56,175 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2023-12-30 21:51:56,176 - INFO - notify_loop - notifier - Starting notif loop
2023-12-30 21:51:56,176 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2023-12-30 21:51:56,333 - INFO - MainThread - scrobbler - Started scrobbler thread.
2023-12-30 21:51:56,341 - ERROR - MainThread - monitor - Config value autoload failed for mpc-be.
Traceback (most recent call last):
  File "C:\Users\flameshikari\AppData\Local\pipx\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 82, in __new__
    cls.config = cls.autoload_cfg()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\flameshikari\AppData\Local\pipx\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 112, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flameshikari\AppData\Local\pipx\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\mpc.py", line 84, in read_player_cfg
    return cls._read_registry_cfg((path1, key1), (path2, key2))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flameshikari\AppData\Local\pipx\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\mpc.py", line 40, in _read_registry_cfg
    error.filename = ",".join(paths)
                     ^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, tuple found
2023-12-30 21:51:56,347 - WARNING - MainThread - main - Could not start monitor for mpc-be
2023-12-30 21:51:56,348 - CRITICAL - MainThread - main - Exiting scrobbler - no more monitors
```
</p>
</details>

**Comment by iamkroot** [comment]
Have you enabled the web interface from the mpcbe Option?

**Comment by flameshikari** [comment]
Yes.

![image](https://github.com/iamkroot/trakt-scrobbler/assets/17804422/44274ef5-d6cf-4a12-b3b3-73c31d674d24)

**Comment by iamkroot** [comment]
Then the next step would be checking the Registry to figure out where the setting is being stored-
1. Open the Registry Editor from start (or `regedit` exec)
2. Navigate to `HKEY_CURRENT_USER\Software\MPC-BE` from the tree-view panel on the left
3. Try to find a `WebServerPort` key somewhere in there.

**Comment by flameshikari** [comment]
I found the issue. I installed MPC-BE via scoop, it stores settings in Player folder instead of Registry by default. Changing settings location to Registry fixes the issue. Is it worth mentioning this in the installation guide?

![2024-01-02_14-07-09_657](https://github.com/iamkroot/trakt-scrobbler/assets/17804422/4c1308bd-54e1-4926-9f0a-f47a4e072e3c)

**Comment by iamkroot** [comment]
Interesting, this seems to be a recent addition to MPC-BE. From what I recall, MPC (and MPCHC) only use the registry.
Rather than changing the mode to registry, you could also use `trakts config set players.mpc-be.port 13579` to manually specify the port number.

On our end, we should support auto-detecting the values from any of these. Will leave this as a TODO.
