### ISSUE TITLE
[BUG] Scrobbler detect the right media but doesn't scrobble on TraktTV

### ISSUE THREAD

**Issue by Skarryy** [iamkroot/trakt-scrobbler#301]
**Describe the bug**

I don't have any error message anywhere, when watching an episode & testing the scrobbler with plex, it does detect the right media but nothing is scrobbled to TraktTV & TraktTV doesn't show the media being played 

**Desktop (please complete the following information):**
 - OS and Version: [OS Ventura 13.6.7]
 - Python Version: [Python 3.11]
 - Player and Version: [Plex Media Server v.1.40.2.8395-c67dce28e]

**To Reproduce**

1. Launch Trakt-Scrobbler
2. Launch Plex Media Server 
3. Launch TV
4. Launch Plex 
5. Play Media 

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
KeyError: 'season'
2024-06-03 08:24:21,728 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 08:24:22,177 - INFO - notify_loop - notifier - Starting notif loop
2024-06-03 08:24:22,177 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 08:24:23,707 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-03 08:54:25,915 - DEBUG - backlog_cleaner - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-03 08:54:25,915 - ERROR - backlog_cleaner - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1394, in run
    self.function(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trakt_scrobbler/backlog_cleaner.py", line 50, in clear
    if trakt.add_to_history(**item) is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trakt_scrobbler/trakt_interface.py", line 148, in add_to_history
    history = prepare_history_data(watched_at, media_info)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trakt_scrobbler/trakt_interface.py", line 139, in prepare_history_data
    {'number': media_info['season'], 'episodes': [
               ~~~~~~~~~~^^^^^^^^^^
KeyError: 'season'
2024-06-03 22:02:17,026 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 22:02:17,372 - INFO - notify_loop - notifier - Starting notif loop
2024-06-03 22:02:17,373 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 22:02:18,125 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-03 22:03:05,214 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 22:03:05,287 - INFO - notify_loop - notifier - Starting notif loop
2024-06-03 22:03:05,288 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 22:03:41,558 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 22:03:41,628 - INFO - notify_loop - notifier - Starting notif loop
2024-06-03 22:03:41,628 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 22:09:49,856 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 22:09:50,369 - INFO - notify_loop - notifier - Starting notif loop
2024-06-03 22:09:50,369 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-03 22:09:52,155 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-03 22:39:52,087 - DEBUG - backlog_cleaner - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-03 22:39:52,087 - ERROR - backlog_cleaner - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1394, in run
    self.function(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trakt_scrobbler/backlog_cleaner.py", line 50, in clear
    if trakt.add_to_history(**item) is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trakt_scrobbler/trakt_interface.py", line 148, in add_to_history
    history = prepare_history_data(watched_at, media_info)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trakt_scrobbler/trakt_interface.py", line 139, in prepare_history_data
    {'number': media_info['season'], 'episodes': [
               ~~~~~~~~~~^^^^^^^^^^
KeyError: 'season'
2024-06-04 17:36:30,575 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-04 17:36:31,137 - INFO - notify_loop - notifier - Starting notif loop
2024-06-04 17:36:31,137 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-04 17:36:33,365 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-04 18:06:33,427 - DEBUG - backlog_cleaner - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-04 18:06:33,427 - ERROR - backlog_cleaner - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1394, in run
    self.function(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trakt_scrobbler/backlog_cleaner.py", line 50, in clear
    if trakt.add_to_history(**item) is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trakt_scrobbler/trakt_interface.py", line 148, in add_to_history
    history = prepare_history_data(watched_at, media_info)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/trakt_scrobbler/trakt_interface.py", line 139, in prepare_history_data
    {'number': media_info['season'], 'episodes': [
               ~~~~~~~~~~^^^^^^^^^^
KeyError: 'season'
2024-06-05 17:23:23,105 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:23:23,589 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:23:23,589 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:23:25,509 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-05 17:40:51,542 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:40:51,666 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:40:51,667 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:40:51,849 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-05 17:41:59,234 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:41:59,299 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:41:59,300 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:42:04,064 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:42:04,130 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:42:04,130 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:42:04,132 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-05 17:42:08,128 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:42:08,193 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:42:08,193 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:42:16,528 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:42:16,592 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:42:16,593 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:42:16,595 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.31, 'media_info': {'type': 'movie', 'title': 'The Fall Guy', 'year': 2024}, 'updated_at': 1717019903.753132}
2024-06-05 17:42:42,344 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:42:42,409 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:42:42,410 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:44:15,334 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:44:15,394 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:44:15,394 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:44:21,843 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:44:21,908 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:44:21,908 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:45:09,472 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:45:09,531 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:45:09,532 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:45:09,550 - INFO - MainThread - monitor - Started monitor for plex
2024-06-05 17:46:01,037 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:46:01,108 - INFO - notify_loop - notifier - Starting notif loop
2024-06-05 17:46:01,109 - DEBUG - MainThread - notifier - Notif actions enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-06-05 17:46:01,116 - INFO - MainThread - monitor - Started monitor for plex
2024-06-05 17:46:01,132 - DEBUG - plex - monitor - action=scrobble
2024-06-05 17:46:01,132 - DEBUG - plex - monitor - {'state': 2, 'progress': 0.01, 'media_info': {'type': 'episode', 'title': 'Samurai Champloo S01', 'season': 1, 'episode': 21, 'year': None}, 'updated_at': 1717602361.1321862}


```
</p>
</details>

**Comment by iamkroot** [comment]
Huh, this one completely went under my radar. Glad you got it working!
