### ISSUE TITLE
[BUG] Sometimes trakt-scrobbler dies after not being able to connect to plex

### ISSUE THREAD

**Issue by soredake** [iamkroot/trakt-scrobbler#305]
**Describe the bug**

Sometimes trakt-scrobbler dies after not being able to connect to plex (`CRITICAL - MainThread - main - Exiting scrobbler - no more monitors`)
This happened 3 times already.

**Desktop (please complete the following information):**
 - OS and Version: Windows 11 Pro
 - Python Version: Python 3.12.4
 - Player and Version: mpv-git
 - Trakt Scrobbler Version: Trakts version 1.7.0-beta.1 (latest git)

**To Reproduce**

1. Setup trakt-scrobbler too monitor plex
2. Shut down plex server
3. trakt-scrobbler will try to connect
4. And then will die `CRITICAL - MainThread - main - Exiting scrobbler - no more monitors` stopping monitoring anything

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```
2024-06-26 13:00:18,577 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B866B200>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:00:18,577 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:00:32,627 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8986990>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:00:32,627 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:00:46,684 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B866AF30>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:00:46,685 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:01:00,760 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8986CC0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:01:00,760 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:01:14,789 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8986780>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:01:14,790 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:01:28,820 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8987EF0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:01:28,821 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:01:42,857 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B89878F0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:01:42,857 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:01:56,898 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B893E120>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:01:56,898 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:02:10,938 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8969160>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:02:10,938 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:02:24,969 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8984080>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:02:24,970 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:02:39,027 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B89862A0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:02:39,027 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:02:53,067 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8984500>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:02:53,067 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:03:07,133 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8987A10>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:03:07,134 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:03:21,170 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8984290>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:03:21,171 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:03:35,206 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B866B4A0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:03:35,206 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:03:49,256 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B896BBF0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:03:49,256 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:04:03,319 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B866B4A0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:04:03,319 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:04:17,358 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8984CB0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:04:17,358 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:04:31,405 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8987BC0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:04:31,405 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:04:45,444 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8987890>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:04:45,445 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:04:59,527 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8986ED0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:04:59,527 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:05:13,592 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B89878F0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:05:13,592 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:05:27,665 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B896B110>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:05:27,665 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:05:41,714 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8976960>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:05:41,715 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:05:55,773 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8987F20>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:05:55,775 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:06:09,833 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8986C90>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:06:09,834 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:06:23,877 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B89864E0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:06:23,879 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:06:37,924 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8984890>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:06:37,925 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:06:51,966 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8987C50>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:06:51,967 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:07:06,004 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8986990>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:07:06,005 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:07:20,046 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8977DA0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:07:20,046 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:07:34,087 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B866B440>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:07:34,088 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:07:48,116 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8986690>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:07:48,117 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:08:02,168 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8987B60>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:08:02,168 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:08:04,500 - DEBUG - syncplay@mpv - monitor - action=scrobble
2024-06-26 13:08:04,500 - DEBUG - syncplay@mpv - monitor - {'state': 0, 'progress': 100.0, 'media_info': {'type': 'episode', 'title': 'GameCenter CX', 'season': 18, 'episode': 20}, 'updated_at': 1719396484.5003207}
2024-06-26 13:08:04,501 - DEBUG - scrobbler - scrobbler - Scrobbling stop at 100.00% for GameCenter CX
2024-06-26 13:08:05,288 - INFO - scrobbler - scrobbler - Scrobble stop successful for GameCenter CX S18E20 at 100.00%
2024-06-26 13:08:10,781 - ERROR - syncplay@mpv - mpv - Error with command ['get_property', 'time-pos']. Response: {'request_id': 8603, 'error': 'property unavailable'}
2024-06-26 13:08:16,207 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8984C20>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:08:16,207 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:08:18,188 - DEBUG - syncplay@mpv - file_info - Raw filepath 'https://youtu.be/t1PCyQYxvsY'
2024-06-26 13:08:18,189 - DEBUG - syncplay@mpv - file_info - Converted to url 'https://youtu.be/t1PCyQYxvsY'
2024-06-26 13:08:18,190 - DEBUG - syncplay@mpv - file_info - Guessit url '/t1PCyQYxvsY'
2024-06-26 13:08:18,190 - INFO - syncplay@mpv - file_info - File path not in whitelist.
2024-06-26 13:08:30,252 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8976D20>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:08:30,252 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:08:44,304 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8976000>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:08:44,305 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:08:58,348 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B896B770>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:08:58,349 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:09:12,379 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B89868A0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:09:12,380 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:09:26,429 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8987C80>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:09:26,429 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:09:40,468 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8986C60>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:09:40,468 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:09:54,515 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B89844A0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:09:54,515 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:10:08,552 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B866B2F0>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:10:08,553 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:10:22,597 - ERROR - plex - utils - Failed to connect: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: /status/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8B8974920>: Failed to establish a new connection: [WinError 10061] ����������� �� �����������, �.�. �������� ��������� ������ ������ �� �����������'))
2024-06-26 13:10:22,597 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:10:32,602 - WARNING - plex - utils - Request failed
2024-06-26 13:10:32,602 - DEBUG - plex - utils - Request: get {'url': 'http://localhost:32400/status/sessions'}
2024-06-26 13:10:32,602 - DEBUG - plex - utils - Response: <Response [503]> {"code":503,"title":"Maintenance","status":"Plex Media Server is currently running startup maintenance tasks."}
2024-06-26 13:10:32,603 - ERROR - plex - monitor - Error while getting data from plex: 503 Server Error: Service Unavailable for url: http://localhost:32400/status/sessions
2024-06-26 13:10:32,618 - WARNING - plex - monitor - plex monitor stopped
2024-06-26 13:41:19,406 - ERROR - syncplay@mpv - mpv - Error with command ['get_property', 'time-pos']. Response: {'request_id': 9593, 'error': 'property unavailable'}
2024-06-26 13:41:19,416 - ERROR - syncplay@mpv - __init__ - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\pipx\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 80, in run
    self.conn_loop()
  File "C:\Users\user\AppData\Local\pipx\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 373, in conn_loop
    data = self._call(self._transact, write_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\pipx\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 286, in _call
    return method(*args)
           ^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\pipx\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 268, in _transact
    err, data = win32pipe.TransactNamedPipe(self.file_handle, write_data, read_buf)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.error: (230, 'TransactNamedPipe', '������������ ��������� ������.')
2024-06-26 13:41:19,468 - CRITICAL - MainThread - main - Exiting scrobbler - no more monitors
```
</p>
</details>

**Comment by iamkroot** [comment]
Should be fixed as in #308
