### ISSUE TITLE
ImportError: DLL load failed while importing win32api: The specified module could not be found.

### ISSUE THREAD

**Issue by GMFalka** [iamkroot/trakt-scrobbler#31]
Hello @iamkroot!

Thank you for this scrobbler!

I got stuck installing it tho. If you have the time, can you help me out?

(Windows 10 64bit)

```
C:\Users\username>"C:\Users\username\Desktop\trakt-scrobbler-master\scripts\windows-install.bat"
Checking pipenv install.

Checking config file
config.toml already exists in "C:\Users\username\AppData\Roaming\trakt-scrobbler\".
Please ensure that it matches sample_config.toml, or the app may crash unexpectedly.

Installing to "C:\Users\username\AppData\Local\trakt-scrobbler"
File not found - trakt_scrobbler
File not found - Pipfile
File not found - Pipfile.lock
Installing dependencies from Pipfile.lock (dc303a)…
Ignoring dbus-python: markers 'sys_platform == "linux"' don't match your environment
Ignoring notify2: markers 'sys_platform != "win32"' don't match your environment
  ================================ 16/16 - 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
Setup complete. Starting device authentication.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\username\AppData\Local\trakt-scrobbler\trakt_interface.py", line 7, in <module>
    from notifier import notify
  File "C:\Users\username\AppData\Local\trakt-scrobbler\notifier.py", line 8, in <module>
    from win10toast import ToastNotifier
  File "C:\Users\username\.virtualenvs\trakt-scrobbler-DTMn-yQC\lib\site-packages\win10toast\__init__.py", line 19, in <module>
    from win32api import GetModuleHandle
ImportError: DLL load failed while importing win32api: The specified module could not be found.
"You can run this script again once the issue is fixed. Quitting.
```

Thank you!

**Comment by GMFalka** [comment]
I had to to an admin elevated `python "C:\Users\Constitude FalkaPC\AppData\Local\Programs\Python\Python38-32\Scripts\pywin32_postinstall.py" -install`
now it works! :)
