### ISSUE TITLE
[BUG] Searching cache, unhandled exception.

### ISSUE THREAD

**Issue by GMFalka** [iamkroot/trakt-scrobbler#34]
Hello @iamkroot!

Found an unhandled exception in the logs. 
Its just an FYI report, i dont think theres so many shows/movies with names like that. :)

The show title is [9-1-1](https://trakt.tv/shows/9-1-1-2018). 
and the guessit module found it as

`MatchesDict([('title', ['9', '1-1'])`

Probably why it throw the script off its rails

```
 - DEBUG - mpchc - file_info - Filepath X:\9-1-1.S03E06.1080p.WEB.x264-TBS\9-1-1.s03e06.1080p.web.x264-tbs.mkv
 - DEBUG - mpchc - file_info - Trying to match custom regex.
 - DEBUG - mpchc - file_info - No regex matches for X:/9-1-1.S03E06.1080p.WEB.x264-TBS/9-1-1.s03e06.1080p.web.x264-tbs.mkv
 - DEBUG - mpchc - file_info - Using guessit module to match.
 - DEBUG - mpchc - file_info - MatchesDict([('title', ['9', '1-1']), ('season', 3), ('episode', 6), ('screen_size', '1080p'), ('source', 'Web'), ('video_codec', 'H.264'), ('release_group', 'tbs'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])
 - DEBUG - scrobbler - trakt_interface - Searching cache.
 - ERROR - scrobbler - main - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\trakt-scrobbler\main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\username\AppData\Local\trakt-scrobbler\scrobbler.py", line 26, in run
    self.scrobble(*scrobble_item)
  File "C:\Users\username\AppData\Local\trakt-scrobbler\scrobbler.py", line 30, in scrobble
    if trakt.scrobble(verb, **data):
  File "C:\Users\username\AppData\Local\trakt-scrobbler\trakt_interface.py", line 185, in scrobble
    scrobble_data = prepare_scrobble_data(**media_info)
  File "C:\Users\username\AppData\Local\trakt-scrobbler\trakt_interface.py", line 169, in prepare_scrobble_data
    trakt_id = get_trakt_id(title, type)
  File "C:\Users\username\AppData\Local\trakt-scrobbler\trakt_interface.py", line 147, in get_trakt_id
    trakt_id = trakt_cache[required_type].get(title)
TypeError: unhashable type: 'list'
```

**Comment by iamkroot** [comment]
Ah nice catch. Thanks for taking the time to go through the logs! I'll add a check for this soon. Plus I've been wanting to update the searching functionality for some time. This gives me a good reason to work on it now :P

**Comment by iamkroot** [comment]
Hey @GMFalka , fixed the bug. Do update and check.
