### ISSUE TITLE
[BUG] Scrobbler keeps dying after a few shows

### ISSUE THREAD

**Issue by GiacomoLaw** [iamkroot/trakt-scrobbler#36]
**Describe the bug**
Hi there, the scrobbler keeps erroring out and dying after a few shows.

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version: 3.6.8
 - Player: VLC
 - Player Version: 3.0.8

**To Reproduce**
1. Open any file
2. Close it and play another
3. Close player
4. See error in log file

**Log file**
<details><summary>Click to see log contents</summary>
<p>

```
2019-11-29 16:45:33,485 - DEBUG - scrobbler - scrobbler - Adding item to history {'state': 2, 'progress': 93.69, 'media_info': {'type': 'movie', 'title': 'Babylon'}, 'updated_at': 1571323903.0709527}
2019-11-29 16:45:33,485 - DEBUG - scrobbler - trakt_interface - Searching cache.
2019-11-29 16:45:42,481 - DEBUG - vlc - file_info - Filepath 'None'
2019-11-29 16:45:42,481 - ERROR - vlc - main - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 93, in run
    self.handle_status_update()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 69, in handle_status_update
    current_state = self.parse_status()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 29, in parse_status
    media_info = get_media_info(self.status['filepath'])
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\file_info.py", line 45, in get_media_info
    file_path = Path(file_path)
  File "d:\python\Lib\pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "d:\python\Lib\pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "d:\python\Lib\pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2019-11-29 16:46:37,077 - INFO - MainThread - scrobbler - Started scrobbler thread.
2019-11-29 16:46:37,077 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 90.49, 'media_info': {'type': 'movie', 'title': 'a bloddy anime afdsfas d'}, 'updated_at': 1567352435.157468}
2019-11-29 16:46:37,077 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:46:37,077 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 92.91, 'media_info': {'type': 'movie', 'title': 'Babylon'}, 'updated_at': 1570449151.6798394}
2019-11-29 16:46:37,077 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:46:37,593 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 93.09, 'media_info': {'type': 'episode', 'title': 'Fate Grand Order', 'season': 1, 'episode': 2}, 'updated_at': 1571069057.9425116}
2019-11-29 16:46:37,593 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:46:37,860 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 92.62, 'media_info': {'type': 'movie', 'title': 'Babylon'}, 'updated_at': 1571213034.0397353}
2019-11-29 16:46:37,860 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:46:38,102 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 93.69, 'media_info': {'type': 'movie', 'title': 'Babylon'}, 'updated_at': 1571323903.0709527}
2019-11-29 16:46:38,102 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:46:38,391 - INFO - MainThread - monitor - Started monitor for vlc
2019-11-29 16:46:50,465 - DEBUG - vlc - file_info - Filepath 'None'
2019-11-29 16:46:50,465 - ERROR - vlc - main - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 93, in run
    self.handle_status_update()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 69, in handle_status_update
    current_state = self.parse_status()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 29, in parse_status
    media_info = get_media_info(self.status['filepath'])
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\file_info.py", line 45, in get_media_info
    file_path = Path(file_path)
  File "d:\python\Lib\pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "d:\python\Lib\pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "d:\python\Lib\pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2019-11-29 16:47:10,374 - INFO - MainThread - scrobbler - Started scrobbler thread.
2019-11-29 16:47:10,375 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 90.49, 'media_info': {'type': 'movie', 'title': 'a bloddy anime afdsfas d'}, 'updated_at': 1567352435.157468}
2019-11-29 16:47:10,375 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:47:10,375 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 92.91, 'media_info': {'type': 'movie', 'title': 'Babylon'}, 'updated_at': 1570449151.6798394}
2019-11-29 16:47:10,375 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:47:10,898 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 93.09, 'media_info': {'type': 'episode', 'title': 'Fate Grand Order', 'season': 1, 'episode': 2}, 'updated_at': 1571069057.9425116}
2019-11-29 16:47:10,898 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:47:11,162 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 92.62, 'media_info': {'type': 'movie', 'title': 'Babylon'}, 'updated_at': 1571213034.0397353}
2019-11-29 16:47:11,162 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:47:11,378 - DEBUG - MainThread - scrobbler - Adding item to history {'state': 2, 'progress': 93.69, 'media_info': {'type': 'movie', 'title': 'Babylon'}, 'updated_at': 1571323903.0709527}
2019-11-29 16:47:11,378 - DEBUG - MainThread - trakt_interface - Searching cache.
2019-11-29 16:47:11,801 - INFO - MainThread - monitor - Started monitor for vlc
2019-11-29 16:47:15,808 - INFO - vlc - monitor - Unable to connect to vlc. Ensure that the web interface is running.
2019-11-29 16:49:00,043 - DEBUG - vlc - file_info - Filepath 'None'
2019-11-29 16:49:00,043 - ERROR - vlc - main - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 93, in run
    self.handle_status_update()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 69, in handle_status_update
    current_state = self.parse_status()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 29, in parse_status
    media_info = get_media_info(self.status['filepath'])
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\file_info.py", line 45, in get_media_info
    file_path = Path(file_path)
  File "d:\python\Lib\pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "d:\python\Lib\pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "d:\python\Lib\pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2019-11-29 16:50:05,286 - DEBUG - MainThread - utils - C:\Users\giaco\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
2019-11-29 16:50:05,287 - DEBUG - MainThread - utils - C:\Users\giaco\AppData\Roaming\trakt-scrobbler\trakt_token.json doesn't exist.
2019-11-29 16:50:05,287 - INFO - MainThread - trakt_interface - Access token not found in config. Initiating device authentication.
2019-11-29 16:50:05,734 - INFO - MainThread - trakt_interface - Verification URL: https://trakt.tv/activate
2019-11-29 16:50:05,734 - INFO - MainThread - trakt_interface - User Code: FD96332A
2019-11-29 16:50:06,034 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2019-11-29 16:50:11,221 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2019-11-29 16:50:16,413 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2019-11-29 16:50:21,608 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2019-11-29 16:50:26,825 - INFO - MainThread - trakt_interface - Device auth successful.
2019-11-29 16:50:26,826 - INFO - MainThread - scrobbler - Started scrobbler thread.
2019-11-29 16:50:26,826 - DEBUG - MainThread - utils - C:\Users\giaco\AppData\Roaming\trakt-scrobbler\watched_cache.json doesn't exist.
2019-11-29 16:50:26,832 - INFO - MainThread - monitor - Started monitor for vlc
2019-11-29 16:50:27,367 - ERROR - vlc - main - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 88, in run
    self.update_status()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\vlc.py", line 40, in update_status
    status_data = self.sess.get(self.status_url).json()
  File "C:\Users\giaco\.virtualenvs\trakt-scrobbler-3Aa1h_Wh\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "d:\python\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\python\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\python\Lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-29 16:51:06,644 - DEBUG - MainThread - utils - C:\Users\giaco\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
2019-11-29 16:51:06,644 - INFO - MainThread - scrobbler - Started scrobbler thread.
2019-11-29 16:51:06,648 - INFO - MainThread - monitor - Started monitor for vlc
2019-11-29 16:51:10,659 - INFO - vlc - monitor - Unable to connect to vlc. Ensure that the web interface is running.
2019-11-29 16:51:20,705 - DEBUG - vlc - file_info - Filepath 'D:/giaco/Documents/Shows/The Apprentice UK/Season 2/The Apprentice UK.S02E10.Episode 10 - Season 2.avi'
2019-11-29 16:51:20,706 - DEBUG - vlc - file_info - Trying to match custom regex.
2019-11-29 16:51:20,706 - DEBUG - vlc - file_info - No regex matches for D:/giaco/Documents/Shows/The Apprentice UK/Season 2/The Apprentice UK.S02E10.Episode 10 - Season 2.avi
2019-11-29 16:51:20,706 - DEBUG - vlc - file_info - Using guessit module to match.
2019-11-29 16:51:20,919 - DEBUG - vlc - file_info - MatchesDict([('country', <Country [GB]>), ('season', 2), ('title', 'The Apprentice'), ('episode', 10), ('episode_title', 'Episode 10 - Season 2'), ('container', 'avi'), ('mimetype', 'video/avi'), ('type', 'episode')])
2019-11-29 16:51:20,919 - DEBUG - scrobbler - trakt_interface - Searching cache.
2019-11-29 16:51:20,919 - DEBUG - scrobbler - trakt_interface - Searching trakt.
2019-11-29 16:51:22,501 - DEBUG - scrobbler - trakt_interface - Trakt ID: 2457
2019-11-29 16:51:22,502 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 2457}}, 'episode': {'season': 2, 'number': 10}}
2019-11-29 16:51:22,831 - INFO - scrobbler - scrobbler - Scrobble start successful.
2019-11-29 16:51:30,945 - DEBUG - scrobbler - trakt_interface - Searching cache.
2019-11-29 16:51:30,945 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 2457}}, 'episode': {'season': 2, 'number': 10}}
2019-11-29 16:51:31,184 - INFO - scrobbler - scrobbler - Scrobble stop successful.
2019-11-29 16:51:40,991 - DEBUG - vlc - file_info - Filepath 'None'
2019-11-29 16:51:40,991 - ERROR - vlc - main - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 93, in run
    self.handle_status_update()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 69, in handle_status_update
    current_state = self.parse_status()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 29, in parse_status
    media_info = get_media_info(self.status['filepath'])
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\file_info.py", line 45, in get_media_info
    file_path = Path(file_path)
  File "d:\python\Lib\pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "d:\python\Lib\pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "d:\python\Lib\pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
</p>
</details>

**Comment by iamkroot** [comment]
Sorry, closed by mistake.

**Comment by iamkroot** [comment]
Looking at the log contents, seems like the error occurs because the `filepath` becomes `None`. It should only happen when VLC sends an unknown/invalid file uri. I've added some checks for this situation to reset the status when this happens, and also to log the invalid uri.

@GiacomoLaw Could you please update, and try reproducing the bug? The log file should now have a line like `Invalid file uri '...'`. Could you share the file now?

**Comment by GiacomoLaw** [comment]
Updated, will update when I have the issue again. Thanks!

**Comment by GiacomoLaw** [comment]
Hi there, here it is:

```
2019-12-03 18:43:00,553 - INFO - scrobbler - scrobbler - Scrobble start successful.
2019-12-03 18:43:14,097 - INFO - vlc - monitor - Unable to connect to vlc. Ensure that the web interface is running.
2019-12-03 18:43:14,097 - DEBUG - scrobbler - trakt_interface - Searching cache.
2019-12-03 18:43:14,097 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 2457}}, 'episode': {'season': 3, 'number': 9}}
2019-12-03 18:43:14,433 - INFO - scrobbler - scrobbler - Scrobble stop successful.
2019-12-03 19:41:35,303 - ERROR - vlc - main - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 88, in run
    self.update_status()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\vlc.py", line 40, in update_status
    status_data = self.sess.get(self.status_url).json()
  File "C:\Users\giaco\.virtualenvs\trakt-scrobbler-3Aa1h_Wh\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "d:\python\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\python\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\python\Lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by iamkroot** [comment]
> Hi there, here it is:
> ...
Sadly, this is a separate bug :sweat_smile: I'll add some code to handle this too, but mainly I'm looking for lines similar to `Invalid file uri '...'` in your log.

**Comment by GiacomoLaw** [comment]
Not seeming to get the other one, only getting one like the one above:

```
2019-12-05 14:05:26,541 - ERROR - vlc - main - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 88, in run
    self.update_status()
  File "C:\Users\giaco\AppData\Local\trakt-scrobbler\player_monitors\vlc.py", line 40, in update_status
    status_data = self.sess.get(self.status_url).json()
  File "C:\Users\giaco\.virtualenvs\trakt-scrobbler-3Aa1h_Wh\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "d:\python\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\python\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\python\Lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Thanks

**Comment by iamkroot** [comment]
Hey @GiacomoLaw, I've pushed a fix for this bug. Could you update and check please?

**Comment by GiacomoLaw** [comment]
Updated, will let you know how it goes.

**Comment by iamkroot** [comment]
@GiacomoLaw any updates?

**Comment by GiacomoLaw** [comment]
No issues so far. Think it’s fixed!
