### ISSUE TITLE
[BUG] No module named 'appdirs'

### ISSUE THREAD

**Issue by TakerMc** [iamkroot/trakt-scrobbler#40]
Hello,

I'm trying to setup the scrobble on my computer, but it doesn't seem to work.

Information about my computer:
 - OS: Debian Buster
 - Python Version: 3.7.3

When I try to exeute the script I have the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/florian/.local/trakt-scrobbler/trakt_interface.py", line 7, in <module>
    from app_dirs import DATA_DIR
  File "/home/florian/.local/trakt-scrobbler/app_dirs.py", line 1, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'
```
So, I've looked if that module `appdirs` is installed, it seems to be the case:

```
$ pip list --user
Package         Version   
--------------- ----------
appdirs         1.4.3     
argcomplete     1.11.0    
babelfish       0.5.5     
certifi         2019.11.28
Click           7.0       
distro          1.4.0     
guessit         3.1.0     
idna            2.8       
pip             19.3.1    
pipx            0.14.0.0  
python-dateutil 2.8.1     
rebulk          2.0.0     
requests        2.22.0    
six             1.13.0    
toml            0.10.0    
urllib3         1.25.7    
userpath        1.3.0
```
Anyone ever faced this issue before ? 

Thanks :)

**Comment by iamkroot** [comment]
Did you use the given install script for the installation? Because, in that case, the script should run automatically

**Comment by TakerMc** [comment]
Yes, I've used the script.

Here's the full log:

```
$ ./linux-install-service.sh 
Checking poetry install.

Checking config file
config.toml already exists in /home/florian/.config/trakt-scrobbler/.
Please ensure that it matches sample_config.toml, or the app may crash unexpectedly.

Installing to /home/florian/.local/trakt-scrobbler/
Updating dependencies
Resolving dependencies... (2.1s)

Writing lock file


Package operations: 12 installs, 0 updates, 0 removals

  - Installing six (1.13.0)
  - Installing babelfish (0.5.5)
  - Installing certifi (2019.11.28)
  - Installing chardet (3.0.4)
  - Installing idna (2.8)
  - Installing python-dateutil (2.8.1)
  - Installing rebulk (2.0.0)
  - Installing urllib3 (1.25.7)
  - Installing appdirs (1.4.3)
  - Installing guessit (3.1.0)
  - Installing requests (2.22.0)
  - Installing toml (0.10.0)
Setup complete. Starting device authentication.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/florian/.local/trakt-scrobbler/trakt_interface.py", line 7, in <module>
    from app_dirs import DATA_DIR
  File "/home/florian/.local/trakt-scrobbler/app_dirs.py", line 1, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'
You can run this script again once the issue is fixed. Quitting.
```

**Comment by iamkroot** [comment]
Weird. Could you please show what the output is for `poetry env info`, after you `cd` into `/home/florian/.local/trakt-scrobbler/`?

**Comment by TakerMc** [comment]
Here's the result:

```
~/.local/trakt-scrobbler$ poetry run which python
/home/florian/.cache/pypoetry/virtualenvs/trakt-scrobbler-3UjRXNDG-py3.7/bin/python
```

**Comment by iamkroot** [comment]
What happens if you try running the install script again?

**Comment by TakerMc** [comment]
Exactly the same thing:

```
./linux-install-service.sh 
Checking poetry install.

Checking config file
config.toml already exists in /home/florian/.config/trakt-scrobbler/.
Please ensure that it matches sample_config.toml, or the app may crash unexpectedly.

Installing to /home/florian/.local/trakt-scrobbler/
Updating dependencies
Resolving dependencies... (1.7s)

Writing lock file


Package operations: 12 installs, 0 updates, 0 removals

  - Installing six (1.13.0)
  - Installing babelfish (0.5.5)
  - Installing certifi (2019.11.28)
  - Installing chardet (3.0.4)
  - Installing idna (2.8)
  - Installing python-dateutil (2.8.1)
  - Installing rebulk (2.0.0)
  - Installing urllib3 (1.25.7)
  - Installing appdirs (1.4.3)
  - Installing guessit (3.1.0)
  - Installing requests (2.22.0)
  - Installing toml (0.10.0)
Setup complete. Starting device authentication.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/florian/.local/trakt-scrobbler/trakt_interface.py", line 7, in <module>
    from app_dirs import DATA_DIR
  File "/home/florian/.local/trakt-scrobbler/app_dirs.py", line 1, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'
You can run this script again once the issue is fixed. Quitting.
```

**Comment by iamkroot** [comment]
Something's definitely off. It shouldn't have shown those `Installing ...` messages again. What's the output of `poetry env info`, inside `/home/florian/.local/trakt-scrobbler/`?

**Comment by TakerMc** [comment]
```
$ poetry env info

Virtualenv
Python:         3.7.3
Implementation: CPython
Path:           /home/florian/.cache/pypoetry/virtualenvs/trakt-scrobbler-3UjRXNDG-py3.7
Valid:          False

System
Platform: linux
OS:       posix
Python:   /usr
```

**Comment by iamkroot** [comment]
Aha! That should've given `Valid: True` if the installation were proper. Next, run `poetry install` inside that directory, followed by `poetry env info` to check if it was successful.

**Comment by TakerMc** [comment]
Thanks for your help, the issue is resolved. 

`poetry install` did not solve the problem, so I've delete the venv with `poetry env remove 3.7`.

Then I ran again the install command and the script worked ! :) 

Thanks again for your help.
