### ISSUE TITLE
[BUG] VLC monitoring not working

### ISSUE THREAD

**Issue by bonswouar** [iamkroot/trakt-scrobbler#49]
**Describe the bugS**
1. Wrong `vlcrc_path`
2. `get_media_info` problem

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.8.2
 - Player: VLC 3.0.8

**To Reproduce**
- Change `config.toml` to monitor VLC : `monitored = ['vlc']`
- Kill `pythonw.exe` process and execute `trakt-scrobbler.bat` (or reboot)
- Play a movie on VLC

**Log file**
1. ***(At launch)***
```
 - ERROR - MainThread - monitor - Config value autoload failed for vlc.
Traceback (most recent call last):
  File "C:\Users\bonswouar\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 20, in __new__
    cls.config = cls.autoload_cfg()
  File "C:\Users\bonswouar\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 36, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "C:\Users\bonswouar\AppData\Local\trakt-scrobbler\player_monitors\vlc.py", line 49, in read_player_cfg
    raise FileNotFoundError(vlcrc_path)
FileNotFoundError: C:\Users\bonswouar\AppData\Roaming\vlc\vlc\vlcrc
```

2. ***(When playing a video)***
```
 - ERROR - vlc - main - Unhandled exception
Traceback (most recent call last):
  File "main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\bonswouar\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 140, in run
    self.handle_status_update()
  File "C:\Users\bonswouar\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 114, in handle_status_update
    current_state = self.parse_status()
  File "C:\Users\bonswouar\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 71, in parse_status
    media_info = get_media_info(self.status['filepath'])
  File "C:\Users\bonswouar\AppData\Local\trakt-scrobbler\file_info.py", line 47, in get_media_info
    if not whitelist_file(file_path):
  File "C:\Users\bonswouar\AppData\Local\trakt-scrobbler\file_info.py", line 17, in whitelist_file
    file_path = cleanup_encoding(file_path)
  File "C:\Users\bonswouar\AppData\Local\trakt-scrobbler\utils.py", line 63, in cleanup_encoding
    enc = sys.stdout.encoding
AttributeError: 'NoneType' object has no attribute 'encoding'
```

**Notes**

I did a dirty workaround for problem 1. although the original code seems correct, that's weird !
And no idea about problem 2.

**Comment by iamkroot** [comment]
@bonswouar Thanks for the bug report! You're right, they are two separate bugs. In the first case, as you said, the code seems to be fine. I don't see why the path is coming out to be incorrect, will experiment a bit. For the second one, I've found the source of the bug, and will push a fix for it soon. 

What exactly was your workaround for the first one?

**Comment by iamkroot** [comment]
Ok never mind, found the issue in the first one. It's a windows specific thing.

**Comment by iamkroot** [comment]
@bonswouar Please update and check that the issue if fixed!

**Comment by bonswouar** [comment]
That works perfectly, thanks @iamkroot !
