### ISSUE TITLE
[BUG] doesnt work

### ISSUE THREAD

**Issue by Elreg** [iamkroot/trakt-scrobbler#50]
**Describe the bug**
Watched shows doesn't pass to trakt

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: [e.g. 3.7.3]  3.8.2
 - Player [e.g. VLC, MPV] MPC-HC 64
 - Player Version [e.g. 1.3.2] 1.9

**Log file**
<details><summary>Click to see log contents</summary>
2020-03-05 01:41:27,438 - DEBUG - MainThread - utils - C:\Users\elreg\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
2020-03-05 01:41:27,438 - DEBUG - MainThread - utils - C:\Users\elreg\AppData\Roaming\trakt-scrobbler\trakt_token.json doesn't exist.
2020-03-05 01:41:27,438 - INFO - MainThread - trakt_interface - Access token not found in config. Initiating device authentication.
2020-03-05 01:41:27,758 - INFO - MainThread - trakt_interface - Verification URL: https://trakt.tv/activate
2020-03-05 01:41:27,758 - INFO - MainThread - trakt_interface - User Code: D9251C4C
2020-03-05 01:41:28,147 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:41:33,421 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:41:38,715 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:41:44,468 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:41:49,738 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:41:55,013 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:00,307 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:05,582 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:10,870 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:16,148 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:21,957 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:27,288 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:32,561 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:37,839 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:43,124 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:48,389 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:53,685 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:42:58,954 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:04,241 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:09,516 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:14,786 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:20,101 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:25,375 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:30,665 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:35,951 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:41,224 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:46,513 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:51,787 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:43:57,077 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:44:02,358 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:44:07,619 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:44:12,906 - DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
2020-03-05 01:44:18,230 - INFO - MainThread - trakt_interface - Device auth successful.
2020-03-05 01:48:11,185 - DEBUG - MainThread - utils - C:\Users\elreg\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
2020-03-05 01:48:11,191 - INFO - MainThread - scrobbler - Started scrobbler thread.
2020-03-05 01:48:11,191 - DEBUG - MainThread - utils - C:\Users\elreg\AppData\Roaming\trakt-scrobbler\watched_cache.json doesn't exist.
2020-03-05 01:48:11,204 - ERROR - MainThread - monitor - Config value autoload failed for mpc-hc.
Traceback (most recent call last):
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 20, in __new__
    cls.config = cls.autoload_cfg()
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 36, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\mpc.py", line 25, in read_player_cfg
    hkey = winreg.OpenKey(winreg.HKEY_CURRENT_USER, subkey)
FileNotFoundError: [WinError 2] Не удается найти указанный файл
2020-03-05 01:48:11,253 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
Traceback (most recent call last):
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 20, in __new__
    cls.config = cls.autoload_cfg()
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 36, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\mpv.py", line 50, in read_player_cfg
    mpv_conf.read_string("[root]\n" + conf_path.read_text())
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1227, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\elreg\\AppData\\Roaming\\mpv\\mpv.conf'
2020-03-05 02:04:35,849 - DEBUG - MainThread - utils - C:\Users\elreg\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
2020-03-05 02:04:35,854 - INFO - MainThread - scrobbler - Started scrobbler thread.
2020-03-05 02:04:35,862 - ERROR - MainThread - monitor - Config value autoload failed for mpc-hc.
Traceback (most recent call last):
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 20, in __new__
    cls.config = cls.autoload_cfg()
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 36, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\mpc.py", line 25, in read_player_cfg
    hkey = winreg.OpenKey(winreg.HKEY_CURRENT_USER, subkey)
FileNotFoundError: [WinError 2] Не удается найти указанный файл
2020-03-05 02:04:35,910 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
Traceback (most recent call last):
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 20, in __new__
    cls.config = cls.autoload_cfg()
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 36, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\mpv.py", line 50, in read_player_cfg
    mpv_conf.read_string("[root]\n" + conf_path.read_text())
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1227, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\elreg\\AppData\\Roaming\\mpv\\mpv.conf'
2020-03-05 02:28:44,500 - DEBUG - MainThread - utils - C:\Users\elreg\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
2020-03-05 02:28:44,501 - INFO - MainThread - scrobbler - Started scrobbler thread.
2020-03-05 02:28:44,503 - ERROR - MainThread - monitor - Config value autoload failed for mpc-hc.
Traceback (most recent call last):
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 20, in __new__
    cls.config = cls.autoload_cfg()
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 36, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\mpc.py", line 25, in read_player_cfg
    hkey = winreg.OpenKey(winreg.HKEY_CURRENT_USER, subkey)
FileNotFoundError: [WinError 2] Не удается найти указанный файл
2020-03-05 02:28:44,510 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
Traceback (most recent call last):
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 20, in __new__
    cls.config = cls.autoload_cfg()
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 36, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\mpv.py", line 50, in read_player_cfg
    mpv_conf.read_string("[root]\n" + conf_path.read_text())
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1227, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\elreg\\AppData\\Roaming\\mpv\\mpv.conf'
2020-03-05 02:36:02,931 - DEBUG - MainThread - utils - C:\Users\elreg\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
2020-03-05 02:37:41,632 - DEBUG - MainThread - utils - C:\Users\elreg\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
2020-03-05 02:37:41,635 - INFO - MainThread - scrobbler - Started scrobbler thread.
2020-03-05 02:37:41,645 - ERROR - MainThread - monitor - Config value autoload failed for mpc-hc.
Traceback (most recent call last):
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 20, in __new__
    cls.config = cls.autoload_cfg()
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 36, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\mpc.py", line 25, in read_player_cfg
    hkey = winreg.OpenKey(winreg.HKEY_CURRENT_USER, subkey)
FileNotFoundError: [WinError 2] Не удается найти указанный файл
2020-03-05 02:37:41,670 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
Traceback (most recent call last):
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 20, in __new__
    cls.config = cls.autoload_cfg()
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 36, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "C:\Users\elreg\AppData\Local\trakt-scrobbler\player_monitors\mpv.py", line 50, in read_player_cfg
    mpv_conf.read_string("[root]\n" + conf_path.read_text())
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1227, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\elreg\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\elreg\\AppData\\Roaming\\mpv\\mpv.conf'
[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/4290255/trakt_scrobbler.log)
<p>

```
*PASTE LOG FILE CONTENTS HERE* (Remove everything between the "```")
Location: "trakt_scrobbler.log" file in the following folder, as per your OS 
Linux: ~/.local/share/trakt-scrobbler
Mac: ~/Library/Application Support/trakt-scrobbler
Windows: %APPDATA%\trakt-scrobbler (paste this in Run Dialog, Win+R)
```
</p>
</details>

**Comment by iamkroot** [comment]
@Elreg Please update to the latest version. The big has been fixed. I had tested with mpc-be and had assumed that it would be the same with mpc-hc, but it wasn't so :stuck_out_tongue:. Mpc-hc scrobbling should work fine now. 

PS: It seems you don't have mpv player installed in your system. In this case, it'd be better to remove it from the `monitored_players`list so that the app doesn't try to look for it every time.
