### ISSUE TITLE
[BUG] crashes scrobbler on w10

### ISSUE THREAD

**Issue by CoLdAs1cE** [iamkroot/trakt-scrobbler#51]
after this happens scrobbler dont work any more! ;(

**yeah i just censored out driver location :P**

A clear and concise description of what the bug/error is.

**Desktop (please complete the following information):**
 - OS: w 10
 - Python Version: 373
 - Player VLC
 - Player Version 3.0.8

**Log file**
<details><summary>Click to see log contents</summary>
<p>

```
2020-03-07 09:30:22,991 - DEBUG - vlc - file_info - Filepath '1337:/TEst/SCORPION (2014-2018) - Complete TV Series, Season 1,2,3,4 S01,S02,S03,S04 - 720p Web-DL x264/Season 3 (2016-17)/SCORPION - S03 E09 - Mother Load (720p - Web-DL).mp4'
2020-03-07 09:30:22,992 - DEBUG - vlc - file_info - Trying to match custom regex.
2020-03-07 09:30:22,992 - DEBUG - vlc - file_info - No regex matches for 1337:/Test/SCORPION (2014-2018) - Complete TV Series, Season 1,2,3,4 S01,S02,S03,S04 - 720p Web-DL x264/Season 3 (2016-17)/SCORPION - S03 E09 - Mother Load (720p - Web-DL).mp4
2020-03-07 09:30:22,992 - DEBUG - vlc - file_info - Using guessit module to match.
2020-03-07 09:30:23,066 - DEBUG - vlc - file_info - MatchesDict([('title', 'SCORPION'), ('year', [2014, 2018]), ('other', 'Complete'), ('release_group', 'TV Series'), ('season', [1, 2, 3, 4]), ('screen_size', '720p'), ('source', 'Web'), ('video_codec', 'H.264'), ('episode', 9), ('container', 'mp4'), ('mimetype', 'video/mp4'), ('type', 'episode')])
2020-03-07 09:30:23,066 - ERROR - vlc - main - Unhandled exception
Traceback (most recent call last):
  File "main.py", line 56, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\Test\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 140, in run
    self.handle_status_update()
  File "C:\Users\Test\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 114, in handle_status_update
    current_state = self.parse_status()
  File "C:\Users\coldasice\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 71, in parse_status
    media_info = get_media_info(self.status['filepath'])
  File "C:\Users\coldasice\AppData\Local\trakt-scrobbler\file_info.py", line 63, in get_media_info
    guess['season'] = int(guess.get('season', 1))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```
</p>
</details>

**Comment by iamkroot** [comment]
Looks like a problem with the file name. You have the folder path `...TV Series, Season 1,2,3,4 S01,S02,S03,S04 - 720p Web-DL x264/Season 3 (2016-17)...` which confuses the app and it thinks that episode is from all 4 seasons. I suggest simply renaming that folder (to something like "Scorpion").

**Comment by CoLdAs1cE** [comment]
i see, didnt read log carefully. I will try that! silly me ;(

**Comment by iamkroot** [comment]
@CoLdAs1cE you're not to blame here 😅
The app should have a better description of the problem that occurred, and it should fail gracefully.

**Comment by CoLdAs1cE** [comment]
yeah true, it just crashes i have to remove it from process and start it again ;(.
well i gave u a bug as well so mby u can fix if it happens to others, took me like 3-4 episodes be4 i noticed they did not get in to trakt :)
