### ISSUE TITLE
[BUG] Problem Connecting Plex Server

### ISSUE THREAD

**Issue by tom-n-pdx** [iamkroot/trakt-scrobbler#52]
**Describe the bug**
Using the latest release of plex server and the software on a Mac the daemon is crashing when trying to connect to the Plex server.

Error is an unhandled exception when trying to write the plex_token.json file.

**Desktop (please complete the following information):**
 - OS: MacOS 19.15.3
 - Python Version: homebrew installed Python 3.7.7
 - Player Plex Server
 - Player Version Version 4.22.2, installed via homebrew

One note - installing  poetry via curl failed, installed via homebrew

**To Reproduce**
Steps to reproduce the behavior
1. setup config file to use Plex and VLC
2. Left plex config as defaults
3. ran install
4. rebooted
5. Went and looked at log file and found error.

**Log file**
<p>
2020-03-21 21:30:15,556 - ERROR - MainThread - main - Unhandled exception
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    main()
  File "main.py", line 73, in main
    mon = Mon(scrobble_queue)
  File "/Users/tshott/Library/trakt-scrobbler/player_monitors/plex.py", line 45, in __init__
    self.token = get_token(**plex_conf)
  File "/Users/tshott/Library/trakt-scrobbler/player_monitors/plex.py", line 32, in get_token
    write_json({"token": token}, PLEX_TOKEN_PATH)
  File "/Users/tshott/Library/trakt-scrobbler/utils.py", line 37, in write_json
    json.dump(data, f, indent=4)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
</p>
</details>

**Comment by iamkroot** [comment]
@tom-n-pdx Looks like the app is failing to fetch the Plex token properly.
I've added some code to log the exact error that occurs. Could you please update and try to run the app again? Then paste the logs here.

**Comment by iamkroot** [comment]
@tom-n-pdx I've revamped the installation process, and also made the plex authentication flow more robust. I recommend giving it a try again.

**Comment by iamkroot** [comment]
Closing due to inactivity.
