### ISSUE TITLE
[BUG] trakts auth, init and run start fail with “Expected maxsize to be an integer or None“

### ISSUE THREAD

**Issue by marek-saji** [iamkroot/trakt-scrobbler#55]
**Describe the bug**
A clear and concise description of what the bug/error is.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Python Version: Python 3.7.5
 - Player VLC version 3.0.8 Vetinari (3.0.8-0-gf350b6b5a7)

**To Reproduce**
1. `apt install pipx && pipx install trakt-scrobbler && trakts init`

```
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

[TypeError]
Expected maxsize to be an integer or None

Traceback (most recent call last):
  File "/home/saji/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/saji/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/saji/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/saji/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/saji/local/src/trakt-scrobbler/trakt_scrobbler/commands.py", line 460, in handle
    from trakt_scrobbler.player_monitors import collect_monitors
  File "/home/saji/local/src/trakt-scrobbler/trakt_scrobbler/player_monitors/__init__.py", line 4, in <module>
    from .monitor import Monitor
  File "/home/saji/local/src/trakt-scrobbler/trakt_scrobbler/player_monitors/monitor.py", line 5, in <module>
    from trakt_scrobbler.file_info import get_media_info
  File "/home/saji/local/src/trakt-scrobbler/trakt_scrobbler/file_info.py", line 7, in <module>
    from trakt_scrobbler.utils import cleanup_encoding
  File "/home/saji/local/src/trakt-scrobbler/trakt_scrobbler/utils.py", line 55, in <module>
    def file_uri_to_path(file_uri: str) -> str:
  File "/usr/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
```

Keeps me from trying the fix for #53 :slightly_smiling_face:

**Comment by marek-saji** [comment]
I have removed previously installed, pre-pipx, trakt-scrobbler with:

```sh
systemctl stop --user trakt-scrobbler
trash-put ~/.local/share/trakt-scrobbler/ ~/.local//trakt-scrobbler/ ~/.cache/pypoetry ~/.config/systemd/user/trakt-scrobbler.service
systemctl --user daemon-reload
```

**Comment by iamkroot** [comment]
Ah, the curse of breaking changes between minor Python versions! Thanks for the report @marek-saji

**Comment by iamkroot** [comment]
Fixed in the new release, try now.

**Comment by marek-saji** [comment]
Works perfectly, thank you! :slightly_smiling_face:
