### ISSUE TITLE
getting an anime tv show mismatch despite clear filename 

### ISSUE THREAD

**Issue by emielregis-008** [iamkroot/trakt-scrobbler#58]
> 2020-04-13 11:41:19,175 - DEBUG - mpc-be - file_info - Filepath '\\HDD2\animetv\Nadia - The Secret of Blue Water (1990)\S01\Nadia - The Secret of Blue Water - S01E08 - Mission to Rescue Nadia.mkv'
2020-04-13 11:41:19,175 - DEBUG - mpc-be - file_info - Trying to match custom regex.
2020-04-13 11:41:19,175 - DEBUG - mpc-be - file_info - Using guessit module to match.
2020-04-13 11:41:19,222 - DEBUG - mpc-be - file_info - MatchesDict([('title', 'Nadia'), ('year', 1990), ('season', 1), ('alternative_title', 'The Secret of Blue Water'), ('episode', 8), ('episode_title', 'Mission to Rescue Nadia'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])
2020-04-13 11:41:19,222 - DEBUG - scrobbler - trakt_interface - Searching cache.
2020-04-13 11:41:19,222 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 41917}}, 'episode': {'season': 1, 'number': 8}}
2020-04-13 11:41:19,733 - INFO - scrobbler - scrobbler - Scrobble start successful.
2020-04-13 11:41:44,047 - DEBUG - scrobbler - trakt_interface - Searching cache.
2020-04-13 11:41:44,047 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 41917}}, 'episode': {'season': 1, 'number': 8}}
2020-04-13 11:41:44,452 - INFO - scrobbler - scrobbler - Scrobble stop successful.
2020-04-13 11:41:58,058 - INFO - mpc-be - monitor - Unable to connect to mpc-be. Ensure that the web interface is running.

The show that is matched and scrobbled: https://trakt.tv/shows/nadia-g-s-bitchin-kitchen 

Custom regex in the past version didn't work as well, I used the regex from your default config file. I'm not savvy enough about coding or regex creation for me to have made my own custom regex.

**Comment by iamkroot** [comment]
This seems out of my control :sweat_smile: The metadata extraction is based on heuristics, and can definitely go wrong. Your best option is definitely to try making a custom regex for this, and I'd be happy to help. 

In this case, assuming all your files of this show follow the same pattern, it can be as simple as `.*/(?P<title>.+?) - S(?P<season>\d+)E(?P<episode>\d+).*`

**Comment by emielregis-008** [comment]
Thanks for the quick reply. I'll try your suggested regex and report back. Thank you.

**Comment by emielregis-008** [comment]
It works now. Thank you. :)

**Comment by emielregis-008** [comment]
One other thing, how do I properly add the custom regex to the config file, latest scrobbler version. I added it manually to the config file in the roaming directory. This breaks the trakts command somehow: 

```
PS C:\Users\jclau> trakts
Traceback (most recent call last):
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\confuse.py", line 782, in load_yaml
    return yaml.load(f, Loader=Loader)
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\yaml\parser.py", line 483, in parse_flow_sequence_entry
    raise ParserError("while parsing a flow sequence", self.marks[-1],
yaml.parser.ParserError: while parsing a flow sequence
  in "C:\Users\jclau\AppData\Roaming\trakt-scrobbler\config.yaml", line 13, column 14
expected ',' or ']', but got '?'
  in "C:\Users\jclau\AppData\Roaming\trakt-scrobbler\config.yaml", line 13, column 19

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jclau\AppData\Local\Programs\Python\Python38-32\Scripts\trakts.exe\__main__.py", line 5, in <module>
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\trakt_scrobbler\__init__.py", line 7, in <module>
    config = confuse.Configuration("trakt-scrobbler", "trakt_scrobbler")
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\confuse.py", line 912, in __init__
    self.read()
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\confuse.py", line 948, in read
    self._add_user_source()
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\confuse.py", line 928, in _add_user_source
    self.add(ConfigSource(load_yaml(filename) or {}, filename))
  File "c:\users\jclau\appdata\local\programs\python\python38-32\lib\site-packages\confuse.py", line 784, in load_yaml
    raise ConfigReadError(filename, exc)
confuse.ConfigReadError: file C:\Users\jclau\AppData\Roaming\trakt-scrobbler\config.yaml could not be read: while parsing a flow sequence
  in "C:\Users\jclau\AppData\Roaming\trakt-scrobbler\config.yaml", line 13, column 14
expected ',' or ']', but got '?'
  in "C:\Users\jclau\AppData\Roaming\trakt-scrobbler\config.yaml", line 13, column 19
```

Config file: 
```players:
    monitored: [mpc-be]
    
fileinfo:

  whitelist: []

  include_regexes:
    movie: []
    episode: [.*/(?P<title>.+?) - S(?P<season>\d+)E(?P<episode>\d+).*]```

The lines as of `fileinfo:` are added manually. I can't quite make sense of the instructions in your readme about the config commands. 

Thank you.

**Comment by iamkroot** [comment]
You need to enclose the regex in double quotes, `[".*/(?P<title>.+?) - S(?P<season>\d+)E(?P<episode>\d+).*", "<another regex>"]` because it contains some special characters. 

> I can't quite make sense of your readme instructions about the config commands to add it in that way.

That's too bad, what was the problem you faced exactly? Are the examples not clear enough?

PS: the command would be `trakts config set --add fileinfo.include_regexes.episode "the regex"`

**Comment by emielregis-008** [comment]
> > I can't quite make sense of your readme instructions about the config commands to add it in that way.
> 
> That's too bad, what was the problem you faced exactly? Are the examples not clear enough?

At least by what I could gather from the examples I wasn't quite sure where to put the dots and underscore in the complete command.

**Comment by iamkroot** [comment]
> At least by what I could gather from the examples I wasn't quite sure where to put the dots and underscore in the complete command.

Hmm, you are correct, that part is pretty vague for someone who doesn't program. Thing is, the `_` is just a normal character, and is a part of the name of the parameter, whereas the `.` is for accessing sub-parameters.

I'll make some changes to the README to clarify this.

**Comment by emielregis-008** [comment]
> 
> 
> This seems out of my control 😅 The metadata extraction is based on heuristics, and can definitely go wrong. Your best option is definitely to try making a custom regex for this, and I'd be happy to help.
> 
> In this case, assuming all your files of this show follow the same pattern, it can be as simple as `.*/(?P<title>.+?) - S(?P<season>\d+)E(?P<episode>\d+).*`

Do you think a custom regex for movies can also help avoid mismatches? So far I had none but would like to minimize the chance of it happening. Would you also write out a custom regex for movies please? I have all my movies named according to this pattern: [movie name] ([release year]) 

Thanks. It comes so easy to you, for me it poses quite the challenge. 

May I also suggest you add example custom regexes for a few standard naming formats? Not as a default in the config file but in the readme.
