### ISSUE TITLE
[Help Needed] MPV monitoring on Mac

### ISSUE THREAD

**Issue by prabapro** [iamkroot/trakt-scrobbler#64]
Hi @iamkroot,

The new CLI is awesome. I'm having an issue with my MPV scrobbling. Here's the log;

```2020-05-24 20:53:38,476 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
Traceback (most recent call last):
  File "/Users/codechilli/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/player_monitors/monitor.py", line 17, in __new__
    cls.config = cls.autoload_cfg()
  File "/Users/codechilli/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/player_monitors/monitor.py", line 34, in autoload_cfg
    loaders = getattr(cls, "read_player_cfg")(auto_keys)
  File "/Users/codechilli/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/player_monitors/mpv.py", line 53, in read_player_cfg
    mpv_conf.read_string("[root]\n" + conf_path.read_text())
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1227, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/codechilli/Library/Application Support/mpv/mpv.conf'
2020-05-24 20:53:38,478 - WARNING - MainThread - main - Could not start monitor for mpv
```

My MPV config location: `/Users/codechilli/.config/mpv/mpv.conf`

PS: I'm not sure whether I have placed the path in my conf file properly (as instructed under [players](https://github.com/iamkroot/trakt-scrobbler#players))

Please help.

Thanks.

**Comment by iamkroot** [comment]
Aah, this is a semi-bug. mpv doesn't follow the MacOS convention of config location, while our app assumes so. I'll push a fix for this soon, thanks for raising the issue!
