### ISSUE TITLE
[BUG] v1.0.0.b7

### ISSUE THREAD

**Issue by prabapro** [iamkroot/trakt-scrobbler#72]
@iamkroot upgraded to b7
```
codechilli@Prabas-MacBook-Air:~$ pipx upgrade trakt-scrobbler
upgraded package trakt-scrobbler from 1.0.0b6 to 1.0.0b7 (location: /Users/codechilli/.local/pipx/venvs/trakt-scrobbler)
```

```
2020-06-07 20:44:32,757 - INFO - MainThread - scrobbler - Started scrobbler thread.
2020-06-07 20:44:32,799 - DEBUG - MainThread - monitor - Autoloaded vlc port = 8001
2020-06-07 20:44:32,799 - DEBUG - MainThread - monitor - Autoloaded vlc password = prepare.486$
2020-06-07 20:44:32,799 - INFO - MainThread - monitor - Started monitor for vlc
2020-06-07 20:44:32,805 - DEBUG - MainThread - monitor - Autoloaded mpv ipc_path = /tmp/mpvsocket
2020-06-07 20:44:32,805 - INFO - MainThread - monitor - Started monitor for mpv
2020-06-07 20:44:32,806 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.
2020-06-07 20:44:32,809 - INFO - vlc - monitor - Unable to connect to vlc. Ensure that the web interface is running.
2020-06-07 20:44:42,958 - DEBUG - vlc - file_info - Filepath '/Users/codechilli/Movies/HIT The First Case [2020]/HIT The First Case [2020].mp4'
2020-06-07 20:44:43,146 - DEBUG - vlc - file_info - Guess: MatchesDict([('title', 'HIT The First Case'), ('year', 2020), ('container', 'mp4'), ('mimetype', 'video/mp4'), ('type', 'movie')])
2020-06-07 20:44:43,147 - ERROR - scrobbler - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/Users/codechilli/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/__init__.py", line 32, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Users/codechilli/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/scrobbler.py", line 19, in run
    self.scrobble(*scrobble_item)
  File "/Users/codechilli/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/scrobbler.py", line 23, in scrobble
    logger.debug(f"Scrobble {verb} at {data['progress']:.2f}% for {data['title']}")
KeyError: 'title'
2020-06-07 20:45:13,415 - INFO - vlc - monitor - Unable to connect to vlc. Ensure that the web interface is running.
2020-06-07 20:45:55,104 - DEBUG - mpv - mpv - Sock closed
2020-06-07 20:45:56,141 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.
2020-06-07 20:46:16,445 - DEBUG - mpv - file_info - Filepath '/Users/codechilli/Movies/Kavaludaari/Kavaludaari.mkv'
2020-06-07 20:46:16,477 - DEBUG - mpv - file_info - Guess: MatchesDict([('title', 'Kavaludaari'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'movie')])
2020-06-07 20:48:56,476 - DEBUG - mpv - mpv - Sock closed
2020-06-07 20:48:57,513 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.

```

**Comment by iamkroot** [comment]
Thanks for the report, fixed!
