### ISSUE TITLE
[BUG] invalid syntax during "trakts init" 

### ISSUE THREAD

**Issue by terenyib** [iamkroot/trakt-scrobbler#74]
**Describe the bug**
I tried to install the application, but I always get this error after choosing player.:
```
Selected: vlc
Remember to configure your player(s) as outlined at https://github.com/iamkroot/trakt-scrobbler#players

[SyntaxError]
invalid syntax (<fstring>, line 1)
```

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Python Version: 3.7.7
 - Player: VLC
 - Player Version: 3.0.10 Vetinari

**To Reproduce**
1. pipx install trakt-scrobbler
```
installed package trakt-scrobbler 1.0.0b8, Python 3.7.7
  These apps are now globally available
    - trakts
done! ✨ 🌟 ✨
```
2. trakts init
```
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C
Select the players that should be monitored (separate using comma): 
 [0] mpc-be
 [1] mpc-hc
 [2] mpv
 [3] plex
 [4] vlc
 > 4 
Selected: vlc
Remember to configure your player(s) as outlined at https://github.com/iamkroot/trakt-scrobbler#players

[SyntaxError]
invalid syntax (<fstring>, line 1)
```
**Log file**
<details><summary>Click to see log contents</summary> 
<p>

```
log file has been created ~/.local/share/trakt-scrobbler/trakt_scrobbler.log but the log is completely empty
```
</p>
</details>

**Comment by iamkroot** [comment]
Woah that looks like a weird bug. Could you run the command again with the verbose flag? `trakts init -v` will show the full traceback.

**Comment by terenyib** [comment]
```
 balu@desktop  ~  trakts init -v
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C
Select the players that should be monitored (separate using comma): 
 [0] mpc-be
 [1] mpc-hc
 [2] mpv
 [3] plex
 [4] vlc
 > 4
Selected: vlc
Remember to configure your player(s) as outlined at https://github.com/iamkroot/trakt-scrobbler#players

[SyntaxError]
invalid syntax (<fstring>, line 1)

Traceback (most recent call last):
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/trakt_scrobbler/commands/init.py", line 56, in handle
    val = self.call('auth')
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/cleo/commands/command.py", line 110, in call
    return command.run(args, self.io)
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/clikit/api/command/command.py", line 116, in run
    return self.handle(self.parse(args), io)
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/balu/.local/pipx/venvs/trakt-scrobbler/lib/python3.7/site-packages/trakt_scrobbler/commands/trakt.py", line 13, in handle
    from trakt_scrobbler import trakt_interface as ti
```

**Comment by iamkroot** [comment]
Oh got it. I recently added some code that uses a new feature of Python 3.8, which is why it's throwing an error for your system. I'll add a workaround for this.

**Comment by iamkroot** [comment]
Give it a try now! And thanks for raising the issue :)

**Comment by iamkroot** [comment]
PS: You'll have to update, see the README

**Comment by terenyib** [comment]
@iamkroot  thanks so much for your effort, it is working now :)
