### ISSUE TITLE
[BUG] Whenever the service starts or stops config.yaml gets messed up

### ISSUE THREAD

**Issue by theGuiltyMan** [iamkroot/trakt-scrobbler#77]
**Describe the bug**
Whenever the service starts or stops the config file changes (see attachment), making the service unable to operate without changing it back.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.7.8
 - Player MPC
 - Player Version 1.9.6

**To Reproduce**
1. Initialize the service with "trakts init" command
2. Don't start the service yet (current config file:)
![Before](https://user-images.githubusercontent.com/15068761/86353020-60399680-bc6f-11ea-99dc-bafae7868174.png)
3. Start the service (config file's contents changes:)
![After](https://user-images.githubusercontent.com/15068761/86353112-721b3980-bc6f-11ea-9c24-1f5d113e7095.png)
4. Cannot use any more of trakts commands because of the exception (see error log)

**Log file**
<details><summary>Click to see log contents</summary> 
<p>

```
2020-07-02 14:18:07,958 - ERROR - MainThread - __init__ - Unhandled exception
Traceback (most recent call last):
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\yaml_util.py", line 86, in load_yaml
    return yaml.load(f, Loader=loader)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 429, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:collections.OrderedDict'
  in "C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml", line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\alptug\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alptug\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alptug\.local\bin\trakts.exe\__main__.py", line 4, in <module>
    from trakt_scrobbler.console import main
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\__init__.py", line 48, in <module>
    config = confuse.Configuration("trakt-scrobbler", "trakt_scrobbler")
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 558, in __init__
    self.read()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 600, in read
    self._add_user_source()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 574, in _add_user_source
    yaml_data = yaml_util.load_yaml(filename, loader=self.loader) \
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\yaml_util.py", line 88, in load_yaml
    raise ConfigReadError(filename, exc)
confuse.exceptions.ConfigReadError: file C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml could not be read: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:collections.OrderedDict'
  in "C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml", line 1, column 1
2020-07-02 14:18:50,372 - ERROR - MainThread - __init__ - Unhandled exception
Traceback (most recent call last):
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\yaml_util.py", line 86, in load_yaml
    return yaml.load(f, Loader=loader)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 429, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:collections.OrderedDict'
  in "C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml", line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\alptug\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alptug\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alptug\.local\bin\trakts.exe\__main__.py", line 4, in <module>
    from trakt_scrobbler.console import main
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\__init__.py", line 48, in <module>
    config = confuse.Configuration("trakt-scrobbler", "trakt_scrobbler")
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 558, in __init__
    self.read()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 600, in read
    self._add_user_source()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 574, in _add_user_source
    yaml_data = yaml_util.load_yaml(filename, loader=self.loader) \
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\yaml_util.py", line 88, in load_yaml
    raise ConfigReadError(filename, exc)
confuse.exceptions.ConfigReadError: file C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml could not be read: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:collections.OrderedDict'
  in "C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml", line 1, column 1

```
</p>
</details>

**Comment by iamkroot** [comment]
What scrobbler version are you using? Did you update recently?

**Comment by theGuiltyMan** [comment]
This was my first time installing so it should be up-to-date.
package trakt-scrobbler 1.0.0b10, Python 3.7.8

**Comment by iamkroot** [comment]
Let's try an experiment. Open up `C:\Users\<Your name>\.local\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\__init__.py` in an editor and delete or comment out line 47, which says `confuse.OrderedDict = dict`. Then restart the app using `trakts start -r` and see the logs.

**Comment by theGuiltyMan** [comment]
This is after commenting out line 47 and restarting with an already bugged config.yaml:

<details><summary>Click to see log contents</summary> 
<p>

```
- ERROR - MainThread - __init__ - Unhandled exception
Traceback (most recent call last):
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\yaml_util.py", line 86, in load_yaml
    return yaml.load(f, Loader=loader)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 429, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:collections.OrderedDict'
  in "C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml", line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\alptug\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alptug\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alptug\.local\bin\trakts.exe\__main__.py", line 4, in <module>
    from trakt_scrobbler.console import main
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\__init__.py", line 48, in <module>
    config = confuse.Configuration("trakt-scrobbler", "trakt_scrobbler")
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 558, in __init__
    self.read()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 600, in read
    self._add_user_source()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 574, in _add_user_source
    yaml_data = yaml_util.load_yaml(filename, loader=self.loader) \
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\yaml_util.py", line 88, in load_yaml
    raise ConfigReadError(filename, exc)
confuse.exceptions.ConfigReadError: file C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml could not be read: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:collections.OrderedDict'
  in "C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml", line 1, column 1

```
</p>
</details>

**Comment by iamkroot** [comment]
@theGuiltyMan I should have clarified. You'll need to manually set the config to the normal (non-buggy) version manually before starting.

**Comment by theGuiltyMan** [comment]
This is with the non-buggy config:
<details><summary>Click to see log contents</summary>
<p>
```
- ERROR - MainThread - __init__ - Unhandled exception
Traceback (most recent call last):
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\yaml_util.py", line 86, in load_yaml
    return yaml.load(f, Loader=loader)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\yaml\constructor.py", line 429, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:collections.OrderedDict'
  in "C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml", line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\alptug\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alptug\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alptug\.local\bin\trakts.exe\__main__.py", line 4, in <module>
    from trakt_scrobbler.console import main
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\__init__.py", line 48, in <module>
    config = confuse.Configuration("trakt-scrobbler", "trakt_scrobbler")
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 558, in __init__
    self.read()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 600, in read
    self._add_user_source()
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\core.py", line 574, in _add_user_source
    yaml_data = yaml_util.load_yaml(filename, loader=self.loader) \
  File "c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\confuse\yaml_util.py", line 88, in load_yaml
    raise ConfigReadError(filename, exc)
confuse.exceptions.ConfigReadError: file C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml could not be read: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:collections.OrderedDict'
  in "C:\Users\Alptug\AppData\Roaming\trakt-scrobbler\config.yaml", line 1, column 1

```
</p>
</details>
Also same with previous, the service starts but the config gets bugged.

**Comment by iamkroot** [comment]
That's weird. I haven't been able to reproduce this on my machine either. Did you install this using pipx?

**Comment by iamkroot** [comment]
Let's try one more thing.
In cmd/powershell, run `c:\users\alptug\.local\pipx\venvs\trakt-scrobbler\Scripts\python.exe -c "import confuse; print(confuse.__version__)"` and check what it prints

**Comment by theGuiltyMan** [comment]
`C:\users\alptug\.local\pipx\venvs\trakt-scrobbler\Scripts> .\python.exe -c "import confuse; print(confuse.__version__)"`
1.3.0

**Comment by iamkroot** [comment]
Ok i was able to reproduce this on my windows setup. Will try solving this locally.

**Comment by iamkroot** [comment]
Fixed in the latest version. Update, and make sure to use the cleaned config before starting the service.
