### ISSUE TITLE
[BUG] Could not start monitor for vlc

### ISSUE THREAD

**Issue by Rostabal** [iamkroot/trakt-scrobbler#94]
**Describe the bug**
It doesn't detect any activity on vlc no matter what file I open.
I did a clean install of Windows. I installed Python 3.9 (I think I had an earlier version before but I don't remember which). I setup everything as it's explained in the wiki. No activity is detected. I've reinstalled both python, vlc and trakt scrobbler, tryed doing it with and without a whitelist and still no activity detected.

**Desktop (please complete the following information):**
 - OS: Windows 10 Education 20H2
 - Python Version: 3.9
 - Player: VLC
 - Player Version: 3.0.11

**To Reproduce**
1. Open any file
2. Play till the end
3. Close player or pause it
4. See error in log file

**Log file**
<details><summary>Click to see log contents</summary> 
<p>

```
2020-11-13 16:48:32,030 - WARNING - MainThread - main - Could not start monitor for vlc
2020-11-14 12:40:59,771 - INFO - MainThread - scrobbler - Started scrobbler thread.
2020-11-14 12:40:59,907 - DEBUG - MainThread - monitor - Autoloaded vlc port = 8080
2020-11-14 12:40:59,907 - ERROR - MainThread - monitor - Config value autoload failed for vlc.
Traceback (most recent call last):
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\configparser.py", line 789, in get
    value = d[option]
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\collections\__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\collections\__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'http-password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\gonca\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 17, in __new__
    cls.config = cls.autoload_cfg()
  File "c:\users\gonca\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 47, in autoload_cfg
    monitor_cfg[param] = param_loader()
  File "c:\users\gonca\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\vlc.py", line 62, in <lambda>
    "password": lambda: vlcrc.get("lua", "http-password"),
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'http-password' in section: 'lua'
2020-11-14 12:40:59,955 - WARNING - MainThread - main - Could not start monitor for vlc
2020-11-15 00:33:55,157 - INFO - MainThread - scrobbler - Started scrobbler thread.
2020-11-15 00:33:55,201 - ERROR - MainThread - monitor - Config value autoload failed for vlc.
Traceback (most recent call last):
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\configparser.py", line 789, in get
    value = d[option]
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\collections\__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\collections\__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'http-password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\gonca\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 17, in __new__
    cls.config = cls.autoload_cfg()
  File "c:\users\gonca\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 47, in autoload_cfg
    monitor_cfg[param] = param_loader()
  File "c:\users\gonca\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\vlc.py", line 62, in <lambda>
    "password": lambda: vlcrc.get("lua", "http-password"),
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'http-password' in section: 'lua'
2020-11-15 00:33:55,228 - WARNING - MainThread - main - Could not start monitor for vlc
2020-11-15 00:40:26,338 - INFO - MainThread - scrobbler - Started scrobbler thread.
2020-11-15 00:40:26,366 - DEBUG - MainThread - monitor - Autoloaded vlc port = 8080
2020-11-15 00:40:26,366 - ERROR - MainThread - monitor - Config value autoload failed for vlc.
Traceback (most recent call last):
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\configparser.py", line 789, in get
    value = d[option]
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\collections\__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\collections\__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'http-password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\gonca\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 17, in __new__
    cls.config = cls.autoload_cfg()
  File "c:\users\gonca\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 47, in autoload_cfg
    monitor_cfg[param] = param_loader()
  File "c:\users\gonca\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\vlc.py", line 62, in <lambda>
    "password": lambda: vlcrc.get("lua", "http-password"),
  File "c:\users\gonca\appdata\local\programs\python\python39\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'http-password' in section: 'lua'
2020-11-15 00:40:26,369 - WARNING - MainThread - main - Could not start monitor for vlc

```
</p>
</details>

**Comment by iamkroot** [comment]
Well, it says right there in the log: `configparser.NoOptionError: No option 'http-password' in section: 'lua'`

You haven't set the password for the web interface in VLC settings, as specified in the [player setup requirements](https://github.com/iamkroot/trakt-scrobbler/wiki/Players-Setup#vlc).

**Comment by Rostabal** [comment]
> Well, it says right there in the log: `configparser.NoOptionError: No option 'http-password' in section: 'lua'`
> 
> You haven't set the password for the web interface in VLC settings, as specified in the [player setup requirements](https://github.com/iamkroot/trakt-scrobbler/wiki/Players-Setup#vlc).

Yeah. Looks like I missed that step. It's fixed now. Thanks.
