### ISSUE TITLE
[BUG] All Pipe Instances Busy

### ISSUE THREAD

**Issue by GaussianCurve** [iamkroot/trakt-scrobbler#99]
Seems like for some reason once a show is completed 100% and the next episode start after. It will say all instances are busy and not detect once the other file has closed.

71 - INFO - scrobbler - scrobbler - Scrobble start successful for Robot Chicken S01E02
2020-12-09 19:58:14,606 - DEBUG - mpv - monitor - action=scrobble
2020-12-09 19:58:14,607 - DEBUG - mpv - monitor - {'state': 0, 'progress': 100, 'media_info': {'type': 'episode', 'title': 'Robot Chicken', 'season': 1, 'episode': 2}, 'updated_at': 1607561894.6062934}
2020-12-09 19:58:14,608 - DEBUG - scrobbler - scrobbler - Scrobbling stop at 100.00% for Robot Chicken
2020-12-09 19:58:14,609 - DEBUG - mpv - mpv - Pipe closed.
2020-12-09 19:58:14,715 - ERROR - mpv - __init__ - Unhandled exception
Traceback (most recent call last):
  File "c:\users\milton\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\__init__.py", line 32, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "c:\users\milton\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 72, in run
    self.conn_loop()
  File "c:\users\milton\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 220, in conn_loop
    self.file_handle = win32file.CreateFile(
pywintypes.error: (231, 'CreateFile', 'All pipe instances are busy.')
2020-12-09 19:58:14,899 - INFO - scrobbler - scrobbler - Scrobble stop successful for Robot Chicken S01E02

**Comment by iamkroot** [comment]
Hmm that's weird indeed. Could you try increasing the `restart_delay` for mpv, and see what happens? `trakts config set players.mpv.restart_delay 0.2`. Also, can you please tell the frequency of this error? For example, does it happen every time you play 5 files in a row? Or is it completely random?

Currently, after a file is stopped, the monitor restarts the connection with mpv, with the default delay being `0.1` seconds. Maybe we're trying to do that too fast? As an aside, I've been eyeing this part of the code and I really don't remember _why_ we need to restart the connection (it's been two years since I wrote this). Probably to support the mpv wrappers. If I get free sometime, I'd like to see if we can remove this step.

**Comment by GaussianCurve** [comment]
I set it to 0..2 and I got the same error in the log again. It seems to happen every second file I play, though to give context to this it happens when I have a playlist on mpv and one file ends and it goes to the next automatically right after.

**Comment by iamkroot** [comment]
I've pushed an update to the monitor so that we don't close the connection after each file ends. This should fix your problems I believe. But I'm not too sure how this will impact the behaviour of mpv wrappers (like smplayer).

To try out the fix, do:
    1. `trakts stop`
    2. `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git@fix-mpv`
    3. `trakts start`

and report back. In the long term, I'd like to switch to using `win32pipe` api for communicating with mpv. I'll try to find some time over a weekend.

**Comment by GaussianCurve** [comment]
I installed the fix and seem to still be getting the pipes instances busy error after like 2 or 3 files are played. Along with a new error now that I haven't experienced before that is in the log below.

2020-12-15 22:21:31,973 - DEBUG - scrobbler - scrobbler - Scrobbling pause at 1.47% for Ben 10
2020-12-15 22:21:32,186 - INFO - scrobbler - scrobbler - Scrobble pause successful for Ben 10 S01E01
2020-12-15 22:22:46,028 - DEBUG - mpv - monitor - action=delayed_play
2020-12-15 22:22:51,032 - DEBUG - Thread-162 - monitor - Delayed scrobble
2020-12-15 22:22:51,033 - DEBUG - Thread-162 - monitor - {'state': 2, 'progress': 1.56, 'media_info': {'type': 'episode', 'title': 'Ben 10', 'season': 1, 'episode': 1, 'year': 2005}, 'updated_at': 1608088966.0287268}
2020-12-15 22:22:51,035 - DEBUG - Thread-162 - monitor - Exiting fast_pause
2020-12-15 22:22:51,035 - DEBUG - scrobbler - scrobbler - Scrobbling start at 1.56% for Ben 10
2020-12-15 22:22:51,338 - INFO - scrobbler - scrobbler - Scrobble start successful for Ben 10 S01E01
2020-12-15 22:28:26,945 - DEBUG - mpv - monitor - action=scrobble
2020-12-15 22:28:26,945 - DEBUG - mpv - monitor - {'state': 1, 'progress': 25.26, 'media_info': {'type': 'episode', 'title': 'Ben 10', 'season': 1, 'episode': 1, 'year': 2005}, 'updated_at': 1608089306.9453788}
2020-12-15 22:28:26,947 - DEBUG - scrobbler - scrobbler - Scrobbling pause at 25.26% for Ben 10
2020-12-15 22:28:27,169 - INFO - scrobbler - scrobbler - Scrobble pause successful for Ben 10 S01E01
2020-12-15 22:29:12,986 - DEBUG - mpv - monitor - action=scrobble
2020-12-15 22:29:12,987 - DEBUG - mpv - monitor - {'state': 2, 'progress': 25.29, 'media_info': {'type': 'episode', 'title': 'Ben 10', 'season': 1, 'episode': 1, 'year': 2005}, 'updated_at': 1608089352.9867408}
2020-12-15 22:29:12,988 - DEBUG - scrobbler - scrobbler - Scrobbling start at 25.29% for Ben 10
2020-12-15 22:29:13,311 - INFO - scrobbler - scrobbler - Scrobble start successful for Ben 10 S01E01
2020-12-15 22:37:01,435 - DEBUG - mpv - monitor - action=scrobble
2020-12-15 22:37:01,435 - DEBUG - mpv - monitor - {'state': 1, 'progress': 58.48, 'media_info': {'type': 'episode', 'title': 'Ben 10', 'season': 1, 'episode': 1, 'year': 2005}, 'updated_at': 1608089821.4350913}
2020-12-15 22:37:01,436 - DEBUG - scrobbler - scrobbler - Scrobbling pause at 58.48% for Ben 10
2020-12-15 22:37:01,655 - INFO - scrobbler - scrobbler - Scrobble pause successful for Ben 10 S01E01
2020-12-15 22:37:39,484 - DEBUG - mpv - monitor - action=scrobble
2020-12-15 22:37:39,485 - DEBUG - mpv - monitor - {'state': 2, 'progress': 58.59, 'media_info': {'type': 'episode', 'title': 'Ben 10', 'season': 1, 'episode': 1, 'year': 2005}, 'updated_at': 1608089859.4844444}
2020-12-15 22:37:39,486 - DEBUG - scrobbler - scrobbler - Scrobbling start at 58.59% for Ben 10
2020-12-15 22:37:39,799 - INFO - scrobbler - scrobbler - Scrobble start successful for Ben 10 S01E01
2020-12-15 22:45:07,831 - DEBUG - mpv - monitor - action=scrobble
2020-12-15 22:45:07,832 - DEBUG - mpv - monitor - {'state': 1, 'progress': 90.33, 'media_info': {'type': 'episode', 'title': 'Ben 10', 'season': 1, 'episode': 1, 'year': 2005}, 'updated_at': 1608090307.8318043}
2020-12-15 22:45:07,832 - DEBUG - scrobbler - scrobbler - Scrobbling pause at 90.33% for Ben 10
2020-12-15 22:45:08,048 - INFO - scrobbler - scrobbler - Scrobble pause successful for Ben 10 S01E01
2020-12-15 22:45:37,916 - DEBUG - mpv - monitor - action=scrobble
2020-12-15 22:45:37,917 - DEBUG - mpv - monitor - {'state': 2, 'progress': 90.4, 'media_info': {'type': 'episode', 'title': 'Ben 10', 'season': 1, 'episode': 1, 'year': 2005}, 'updated_at': 1608090337.9161704}
2020-12-15 22:45:37,917 - DEBUG - scrobbler - scrobbler - Scrobbling start at 90.40% for Ben 10
2020-12-15 22:45:41,202 - INFO - scrobbler - scrobbler - Scrobble start successful for Ben 10 S01E01
2020-12-15 22:48:10,082 - DEBUG - mpv - mpv - Exception while writing to pipe.
Traceback (most recent call last):
  File "c:\users\milton\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\player_monitors\mpv.py", line 230, in conn_loop
    win32file.WriteFile(
pywintypes.error: (232, 'WriteFile', 'The pipe is being closed.')
2020-12-15 22:48:10,303 - DEBUG - mpv - mpv - Pipe closed.
2020-12-15 22:48:10,505 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.

**Comment by iamkroot** [comment]
Don't worry about that new exception, it's benign and the code already handles it properly. It shouldn't have been printed to the log file. Are you sure you're getting pipe instances busy error even now?
